### ISSUE TITLE
Add some figures/shapes preset for a quick montaging/composing

### ISSUE THREAD

**Issue by BoQsc** [maoschanz/drawing#1]
**The main point:** Adding some pointing arrow presets would greatly increase quality of bug reporting in other Gnome projects, especially for bug testers and reviewers aswell the programmers themselves.

Gnome have a built-in screenshot integration and quick-editing those screenshots to clarify some things in them would be a very good addition to Gnome project.

So far: Drawing is Very nice, very cool. :clap: :clap:

**Comment by maoschanz** [comment]
It was planned, the "line" tool has an option for it (which isn't implemented yet because there are more urgent bugs)

**Comment by maoschanz** [comment]
What i just did is not the most elegant arrows i've ever seen but i will consider the issue fixed

**Comment by BoQsc** [comment]
These are great, thank you. Although it took me some time to realize how to use them.

![Screencast-from-2020-02-13-16_31_18](https://user-images.githubusercontent.com/21064622/74445094-82787680-4e7e-11ea-8233-a9719e17445a.gif)
