### ISSUE TITLE
Render broken

### ISSUE THREAD

**Issue by Akiyamka** [maoschanz/drawing#102]
## Description
First of all - ui looks nice! I love it. But when i try use it...

Image show and disappear, partly zooming, just see it https://gfycat.com/ifr/HealthyBetterCornsnake
## Steps to reproduce the bug:

1. Install
2. Open app
3. Try to draw smt

----

## System

- Device (desktop computer/tablet/phone/...): HP Spectre x360 Convertible 15-bl1XX
- OS: Clear Linux OS x86_64
- Desktop environment: GNOME 3.32.2
- Package format (flatpak, DEB, AUR ?): flatpak
- App version: 0.4.4

## Additional context
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
GPU: NVIDIA GeForce MX150 
GDM

```
> glxinfo
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)  (0x5917)
    Version: 19.3.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
OpenGL core profile version string: 4.6 (Core Profile) Mesa 19.3.0-devel
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL version string: 3.0 Mesa 19.3.0-devel
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by maoschanz** [comment]
Does it happens only with the selection? If yes, is it worse if you select the "freehand selection" option in the bottom bar?

**Comment by Akiyamka** [comment]
"freehand selection" show the same behavior when after selection closed.
About other tools:
Switch between some tools scale image about x2. Pencil <-> Saturate,  Selection <-> Flip for example

**Comment by maoschanz** [comment]
the app uses the flatpak runtime 3.34 since yesterday, did it improve something?
