### ISSUE TITLE
Change background color of the "canvas"

### ISSUE THREAD

**Issue by amivaleo** [maoschanz/drawing#121]
Hi!

The background color of the main window is quite light. It's a bit hard to understand the border of the image surface, which is white.

Can you please consider using a darker color (for example the one used in gnome-books)? Or maybe ad a border or a shadow that surrounds the image?

**Comment by maoschanz** [comment]
>The background color of the main window is quite light

... if you're using a light theme

>the image surface, which is white

... if you set it that way

![Capture d’écran de 2019-11-23 16-36-53](https://user-images.githubusercontent.com/19996113/69481200-7b0d7800-0e0f-11ea-9578-dc61b643694f.png)

I don't know what i'll do about it, but it's a problem more complex than overriding the theme CSS with custom CSS (which would already be complex)

**Comment by amivaleo** [comment]
> if you're using a light theme

Right! I banned the dark version of adwaita. 🤔

> overriding the theme CSS

Don't, please. I assumed there was a way to select the color from a palette, which is part of the theme.

> if you set it that way

That's the default way, isn't it?

**Comment by maoschanz** [comment]
Yes white is the default value, but i can't just put an other background color and assume it's fixed: someone may use a non-white background. The better thing i could think about is a checkboard pattern, but i don't know how to do it yet.

In my opinion, this issue is related to #14: instead of just displaying the picture on a GtkDrawingArea i should build something more complex to frame it and center it. Once issue #14 will be fixed maybe better ideas will come

**Comment by amivaleo** [comment]
Ok. 💪

I give here one last idea: something like the shadow effect on photoshop might be good too.

Thanks for considering this issue. 💪

**Comment by maoschanz** [comment]
>the shadow effect on photoshop

Do you have a screenshot of it?

**Comment by amivaleo** [comment]
> > the shadow effect on photoshop
> 
> Do you have a screenshot of it?

Not really. I googled that: https://industrydev.com/wp-content/uploads/2015/09/photoshop-light-color-theme-1024x707.jpg

It's just a very thin and light shadow.

**Comment by fabiocolacio** [comment]
@maoschanz why not do something like this in the ``on_draw()``? Here I hard-coded red, but the color could be set in the preferences.

```python
	def on_draw(self, area, cairo_context):
		"""Signal callback. Executed when self.drawing_area is redrawn."""

		# Fill background with a color
		allocation = self.get_allocation()
		cairo_context.new_path()
		cairo_context.set_source_rgb(1, 0, 0)
		cairo_context.move_to(0, 0)
		cairo_context.rel_line_to(allocation.height, 0)
		cairo_context.rel_line_to(allocation.height, allocation.width)
		cairo_context.rel_line_to(0, allocation.width)
		cairo_context.close_path()
		cairo_context.fill()
		cairo_context.paint()

		# Draw the image on top
		cairo_context.scale(self.zoom_level, self.zoom_level)
		cairo_context.set_source_surface(self.get_surface(), \
		                                 -1 * self.scroll_x, -1 * self.scroll_y)
		cairo_context.paint()

		self.active_tool().on_draw(area, cairo_context)
```
It produces the following result:

![custom-background](https://user-images.githubusercontent.com/5248352/77834749-243ce580-7104-11ea-82a9-371f8046d578.png)

**Comment by maoschanz** [comment]
this cairo context is the one used for actually drawing, isn't it? i think any transparency would be replaced by the chosen background color, try to play with the selection and save, i guess you'll have some unwanted red

**Comment by fabiocolacio** [comment]
In ``on_draw()``, the surface being drawn to is the gtk widget itself. This is a different surface than the one your tools draw onto (which would be the ``self.surface`` in that class), which contains the actual drawing. In other words, drawing here does not affect the underlying image data. It works for the same reason that your ``cairo_context.scale()`` does not actually make the image bigger, it just zooms it in on the widget.

I tested saving an image with a transparent background and there was no red.

**Comment by maoschanz** [comment]
ah yes you're right, i completely forgot how that part works

however i'm not sure about the cairo context manipulations you did: isn't the path filling redundant with the "paint()"? this method is executed a lllllllot of times, so i would prefer if it was just like 

```python3
		cairo_context.set_source_rgba(1, 0, 0, 0)
		cairo_context.paint()
```

i can't test it right now, if it works you can put it in the same PR as issue 14 (with a completely transparent color for now, i'll do the preferences dialog later)
