### ISSUE TITLE
Snap package is probably using a branch/version where code is shit

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#125]
https://github.com/kenvandine/drawing/blob/33155c2f6755521dbca827424ef4e7006e632853/meson.build#L3 "0.5.0"? really? what a bruh moment

**Comment by popey** [comment]
Thanks for letting us know. Apologies, this was a mistake. It's been reverted back to 0.4.8.

**Comment by maoschanz** [comment]
Isn't the advantage of snap its whole stable/beta/edge channels thing? I'm not against providing unstable versions, but they should be labelled as unstable

**Comment by kenvandine** [comment]
I had automated builds of master, which I've switched to be based on the 0.4 branch.

**Comment by maoschanz** [comment]
Thanks, i just hope the users (i can't see non-french reviews on GNOME Software) weren't numerous enough back in september when i broke everything in the app

I understand that "edge" has to rely on automated builds from a branch (and it can be master? i suppose people selecting that channel know what they do), but isn't the "stable" channel supposed to rely on my releases regardless of the branch they're from?
