### ISSUE TITLE
edition should be edit/editing

### ISSUE THREAD

**Issue by scootergrisen** [maoschanz/drawing#131]
I think "edition" have been spelled incorrect in multiple files.
Edition is like "nightly edition" of some software.
But it seems it have been used where "edit" or "editing" should be used.

One example:
https://github.com/maoschanz/drawing/blob/e1f755c9a1e7cbfe3cf68f1975782831cacc6025/src/ui/shortcuts.ui#L130

I will let others decide what the correct word should be.

**Comment by maoschanz** [comment]
sorry you're right, in french it's "Édition" everywhere i didn't pay attention
