### ISSUE TITLE
Change "Use dashes" to "Dashes"

### ISSUE THREAD

**Issue by scootergrisen** [maoschanz/drawing#135]
Maybe change "Use dashes" to just "Dashes" or maybe "Dashed".

**Comment by scootergrisen** [comment]
Also see "With dashes".
Maybe thats an old unused string.

**Comment by maoschanz** [comment]
>Also see "With dashes".
Maybe thats an old unused string.

it's written in the window subtitle when dashed are used, i wanted to change it later but maybe it'll be removed

Concerning "Use dashes", i prefer less ambiguous labels so i'll keep it
