### ISSUE TITLE
Close the options menu once an option has changed

### ISSUE THREAD

**Issue by scootergrisen** [maoschanz/drawing#140]
I dont like how the options menu is in way of the drawing/picture.

![Options menu](https://maoschanz.github.io/drawing/screenshots/gnome_arc.png)

If i have to change an option i have to click (1) to open, click (2) to select something, click (3) to close then.
Then i want to change something again so i have to click (4) to open, click (5) to select something, click (6) to close.

That quickly becomes a lot of clicks.

Not sure what the best solution would be.
Sometimes there seems to be only one choice to make so the menu could close after a choice is made but of course that might be annoying when you want to make more then more choice.

**Comment by maoschanz** [comment]
Please if you want to open issues which don't concern actual bugs, don't click on the "bug report" issue template, just open a normal issue
