### ISSUE TITLE
Addition of the 'eraser' tool.

### ISSUE THREAD

**Issue by Bundy01** [maoschanz/drawing#149]
## Suggested solution

It would be interesting to add the eraser with the other tools to retouch the photos with more precision.

Regards.

**Comment by maoschanz** [comment]
when you say an eraser, are you talking about erasing the content of the pixels to get "nothing" (just transparent pixels, or secondary color pixels), or about far more advanced features like trying to replace a part of the picture based on the neighbouring areas?

**Comment by Bundy01** [comment]
Basically, I thought of an eraser as in Gimp. But if it is possible to choose between erasing pixels (transparency) or replacing pixels with the main or secondary color, it is even better :)

**Comment by maoschanz** [comment]
It's not as straightforward as a dedicated "eraser" tool, but these features exist. Based on my own use of MS Paint, I assumed people would mostly use the color of their background as the right-click color, thus they could erase with it. The cases not covered by this are when the background color is semi-transparent (or 100% transparent). If it's your situation, the solution is provided as an option of the pencil tool:

I'm not sure what the version 0.4.x provides, but if i remember correctly, in the pencil (and line, and curve) options you have a section named "mode", with choices like "classic", "source color" and "eraser" (and probably something else)

- "classic" means it'll add the color corresponding to the mouse button you use on top of the existing image (so semi-transparent yellow pencil on blue image = green)
- "source color" means it will replace the pixels with the color corresponding to the mouse button you use (so semi-transparent yellow pencil on blue image = semi-transparent yellow)
- "eraser" doesn't care about the colors you chose and replace anything with transparent pixels

(Be careful, this option is common to these 3 tools, changing the mode of the pencil changes the line and the curve too)

**Comment by maoschanz** [comment]
I should have explained that in the user help documentation maybe lol

**Comment by Bundy01** [comment]
Hi,
I never thought I'd find this kind of tool in a pencil. I'm fine with this, you can close this issue if you want to.
Regards.
