### ISSUE TITLE
The message on exit screen to discard image is wrong in Brazilian Portuguese

### ISSUE THREAD

**Issue by riquena969** [maoschanz/drawing#170]
## When I click the Close button, the "discard" button has a Portuguese error. It says "Discartar" instead of "Descartar".

![screenshot](https://user-images.githubusercontent.com/17579826/72833271-3b270d80-3c65-11ea-8eae-d1e6fc7e7191.png)

## Steps to reproduce the bug:

1. Open the app
2. Draw something
3. Click on close

----

## System

- Device (desktop computer/tablet/phone/...): Desktop
- OS: Linux Mint 19.3 64bit
- Desktop environment: Cinnamon
- Package format (flatpak, native package, snap?): Native
- App version: 0.4.7

**Comment by maoschanz** [comment]
it has been fixed a few months ago, and the fix has been backported to the 0.4 branch by this commit ddaef2b46b9875b6a916ae5037498c0f900fbc4a which has been released with the version 0.4.8, so i'll close the issue. I'm not aware of the linux mint policy regarding updates, but as soon as they upgrade the app it will be fixed for you too

**Comment by maoschanz** [comment]
What a monstruous commit lmao, i didn't remember i backported so many minor changes. Here is a more usable link to what i wanted to show https://github.com/maoschanz/drawing/commit/ddaef2b46b9875b6a916ae5037498c0f900fbc4a#diff-931a113ad399b4dd0ec1d667680c6c35R685

**Comment by riquena969** [comment]
Thanks :)
