### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by bertob** [maoschanz/drawing#18]
I took a stab at an icon in the new style:

![image](https://user-images.githubusercontent.com/1908896/54357273-0538f600-465e-11e9-84ff-621e78aa073e.png)

The crayon metaphor seemed appropriate for the featureset the app currently has, but we can iterate on that :)

**Comment by maoschanz** [comment]
The crayon is good, maybe it could be drawing something "more freehand" (a kind of S or a wave instead of an horizontal line for example ?)

**Comment by maoschanz** [comment]
(for now i'm using the icon from Newaita, of course it's not consistent with Adwaita but it's not ugly like my previous icon, so there is no need to hurry)

**Comment by bertob** [comment]
Maybe something in this direction? I'm not sure if it's too busy for the otherwise very geometric style

![image](https://user-images.githubusercontent.com/1908896/54373072-e9911800-467c-11e9-9d06-3d565172fca1.png)

**Comment by maoschanz** [comment]
i prefer the horizontal one, this one looks too much like gedit

**Comment by bertob** [comment]
How about this?

![image](https://user-images.githubusercontent.com/1908896/54525611-e34cb580-4974-11e9-9570-99a1f7e56662.png)

**Comment by maoschanz** [comment]
it looks fine to me, i'm just not sure about the holes at the top of the sheet, i notice them only now, they seem unnecessary (the metaphor works without them in my opinion)

**Comment by bertob** [comment]
Fair enough, the holes are maybe a bit too much detail at the top.

**Comment by bertob** [comment]
I think this is fine:

![image](https://user-images.githubusercontent.com/1908896/55635142-484f3a80-57c0-11e9-938b-f077f8d4f818.png)

If it's ok with you I can give you the SVG assets.

**Comment by maoschanz** [comment]
(sorry i didn't see the email)

Yes it's perfect, thank you!

**Comment by bertob** [comment]
Here are the hicolor and symbolic in a zip (Github doesn't allow svg uploads):

[com.github.maoschanz.Drawing.zip](https://github.com/maoschanz/drawing/files/3130432/com.github.maoschanz.Drawing.zip)
