### ISSUE TITLE
drawing: set_text(): Gtk.py:757:set_text:TypeError: Argument 1 does not allow None as a value

### ISSUE THREAD

**Issue by tim77** [maoschanz/drawing#181]
## Description

Crashing in some conditions.

## System

- Device: Desktop
- OS: Fedora 31
- Desktop environment: ?
- Package format: Native package
- App version: 0.4.9

## Downstream bug report with full backtrace and debug information

[RHBZ#1798147](https://bugzilla.redhat.com/show_bug.cgi?id=1798147)

**Comment by maoschanz** [comment]
>in some conditions

pasting when the clipboard is empty
