### ISSUE TITLE
Let the people choose if they want to import an image at the start of the program

### ISSUE THREAD

**Issue by BoQsc** [maoschanz/drawing#185]
## Problem

After launching GNOME DRAW, it can be seen that blank new image is being suggested to be drawn on. 

And if you copy an image from clipboard and paste it into GNOME DRAW the clipboard image will be merged with the blank white page that the GNOME DRAW started with.

I only wanted the clipboard image, not a clipboard image merged with white blank page GNOME DRAW starts with on the launch of the program.

Instead the image from the clipboard should be cropped.

![Screencast from 2020-02-13 18_25_55](https://user-images.githubusercontent.com/21064622/74455758-81e7dc00-4e8e-11ea-86f6-58ee8869c852.gif)

## Suggested solution
**At the start of the GNOME Drawing** If nobody drawed on a blank page and someone imports/or use clipboard - please import the image and set the image size to the imported image size.

Better off, simply let the users of GNOME Draw to simply choose if they want to import an image or create a new one, at the start of the program.

**Comment by maoschanz** [comment]
concerning the clipboard, it already exists

![Capture d’écran de 2020-02-13 18-28-09](https://user-images.githubusercontent.com/19996113/74461435-d12e0c80-4e8e-11ea-8d3f-5ebd2de7967f.png)

also available from the "new image" menu (probably under the name "new image from clipboard), however i don't remember if the blank, unedited image is replaced by the new one

concerning the import, i don't think it makes sense
