### ISSUE TITLE
2 warnings on installing on Ubuntu 20.04: `not` and `is not` instead of `==` and `!=`

### ISSUE THREAD

**Issue by R1nzwind** [maoschanz/drawing#190]
## Description

Errors on installing on Ubuntu Budgie

> /usr/lib/python3/dist-packages/drawing/options_manager.py:43: SyntaxWarning: "is
> " with a literal. Did you mean "=="?
>   if action.get_state_type().dup_string() is 's':
> /usr/lib/python3/dist-packages/drawing/selection_manager.py:71: SyntaxWarning: "
> is not" with a literal. Did you mean "!="?
>   if pts[1] is not ():

### Steps to reproduce the bug

1. use python 3.8
2. sudo apt install drawing

## System

- Device: desktop
- OS: Ubuntu Budgie 20.04
- Desktop environment: Budgie
- Package format: native package
- App version: 0.4.10

**Comment by Amr-Ibra** [comment]
On Ubuntu 20.04 focal development with Python 3.8 as default
In a terminal: sudo apt install drawing
Look at the warnings:

drawing (0.4.11-1) is being installed ...
/usr/lib/python3.8/subprocess.py:838: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
/usr/lib/python3/dist-packages/drawing/options_manager.py:43: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if action.get_state_type().dup_string() is 's':
/usr/lib/python3/dist-packages/drawing/selection_manager.py:71: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if pts[1] is not ():
/usr/lib/python3/dist-packages/drawing/selection_manager.py:147: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if pts[1] is not ():
/usr/lib/python3/dist-packages/drawing/selection_manager.py:210: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if pts[1] is not ():
/usr/lib/python3/dist-packages/drawing/selection_manager.py:271: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if pts[1] is not ():
/usr/lib/python3/dist-packages/drawing/tool_experiment.py:285: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pts[1] is ():
/usr/lib/python3/dist-packages/drawing/tool_experiment.py:324: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pts[1] is ():
/usr/lib/python3/dist-packages/drawing/tool_experiment.py:372: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pts[1] is ():
/usr/lib/python3/dist-packages/drawing/tool_select.py:276: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if pts[1] is not ():
/usr/lib/python3/dist-packages/drawing/utilities.py:391: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pts[1] is ():

### **System**
- Device: desktop
- OS: Ubuntu 20.04 focal development
- Desktop environment: GNOME
- Package format: native deb package
- App version: 0.4.11

**Comment by maoschanz** [comment]
I'll wait for python 3.8, currently i don't have any of these warnings

**Comment by Amr-Ibra** [comment]
Python 3.8 is going to be the default for Ubuntu 20.04 LTS.

**Comment by maoschanz** [comment]
ok but i can't fix a bug i can't reproduce

**Comment by maoschanz** [comment]
Does the attached version entirely fix the issue?

[drawing_0.4.12_all.zip](https://github.com/maoschanz/drawing/files/4259035/drawing_0.4.12_all.zip)

**Comment by maoschanz** [comment]
i see 20.04 began its freeze yesterday so i would appreciate if you answer quickly so i could release this version (maybe it's too late anyway? i'm not sure if they would manage this as a bug fix or as a debian import)

**Comment by Amr-Ibra** [comment]
Yes, it fixes the warnings while installing, however, I can still see one warning when run from terminal:

$ drawing 
/usr/share/drawing/drawing/selection_manager.py:272: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if pts[1] is not ():
