### ISSUE TITLE
Canvas display is broken with HiDPi

### ISSUE THREAD

**Issue by prokoudine** [maoschanz/drawing#207]
Switching between classic tools and cropping/transformation completely messes up canvas rendering.

Video: https://youtu.be/cp7_sskJYO4

This is git commit d4fe7a0b84f157d3e4d4e7198423617882261318

**Comment by maoschanz** [comment]
is it an HiDPi screen?

**Comment by prokoudine** [comment]
Yes, it's a HiDPI display

**Comment by maoschanz** [comment]
And is the bug "fixed" when you turn off UI scaling?

**Comment by prokoudine** [comment]
I have no idea how to disable HiDPI scaling in GNOME completely :)

Just how to tweak the scale factor.

**Comment by maoschanz** [comment]
if you set "100%" i suppose it's disabled?

**Comment by prokoudine** [comment]
It's not like that at all :)

The factor is a variable with the lowest value of 0.5, where 1.0 is fully scaled UI. I usually set it to 0.85 otherwise everything is too large for me.

When I set it to 0.5, everything is tiny but Drawing still renders the canvas incorrectly.

**Comment by maoschanz** [comment]
wait till i ~~steal~~ *ask in the context of coronavirus teleworking policies* a laptop with hidpi at my work

**Comment by prokoudine** [comment]
LOL, feel free to ping me to test stuff whenever you like :)

**Comment by maoschanz** [comment]
using fractional scaling on a laptop with ancient linux mint was harder than expected, but anyway i achieved it with a focal fossa VM

And the main clue i found for any future investigation is:

- it doesn't happen with "skew" tool 🤔
