### ISSUE TITLE
Question: What font I am missing here?

### ISSUE THREAD

**Issue by zer09** [maoschanz/drawing#216]
My fonts is not working with Drawing. What font I missed to install?

![Screenshot from 2020-04-13 17-24-51](https://user-images.githubusercontent.com/780780/79109999-1a75dc00-7dac-11ea-881f-25103d94c9ba.png)

## System

- Device: Desktop
- OS: Pop OS 19.10
- Desktop environment: GNOME 3.34.2
- Package format: snap
- App version: 0.4.7-15-g011868f86f

**Comment by maoschanz** [comment]
It looks like a snap issue ![](https://www.zupimages.net/up/20/15/wuqo.png) sorry i've no idea what is broken here

**Comment by zer09** [comment]
Closing, I used flatpak to solve the problem.
