### ISSUE TITLE
Better handle unrecognized image formats

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [maoschanz/drawing#217]
## Description

 I see the message of my title.

![image](https://user-images.githubusercontent.com/47056543/79191391-5fd2f180-7e1e-11ea-82c7-b26cf5351054.png)

### Steps to reproduce the bug

1. Download the picture that is a panel of people's faces ('3292.jpg') from [this site](https://www.theguardian.com/news/2020/apr/13/coronavirus-looking-for-good-news-run-for-heroes-and-an-opera-singing-doctor#img-2).
2. Try to open it in Drawing.

## System

- Device (desktop computer/tablet/phone/...): Laptop
- OS: Mint 19.3
- Desktop environment: CInnamon
- Package format (flatpak, native package, snap?): native
- App version: 0.4..7

I imagine the image is obfuscated; other programs have trouble opening it too. Still, you program says 'please report' . .

Other jpegs seem to open alright, but I have not used the program much.

Please note also that the error message is ungrammatical: its comma should be a full-stop. (Commas cannot be used to conjoin clauses that could stand on their own as independent sentences,)

**Comment by maoschanz** [comment]
```
Traceback (most recent call last):
  File "/usr/share/drawing/drawing/main.py", line 198, in on_cli
    self.open_window_with_content(f, False)
  File "/usr/share/drawing/drawing/main.py", line 139, in open_window_with_content
    win.init_window_content(gfile, get_cb) # this optimization has no effect
  File "/usr/share/drawing/drawing/window.py", line 121, in init_window_content
    self.build_new_tab(gfile=gfile)
  File "/usr/share/drawing/drawing/window.py", line 248, in build_new_tab
    new_image.try_load_file(gfile)
  File "/usr/share/drawing/drawing/image.py", line 160, in try_load_file
    pixbuf = GdkPixbuf.Pixbuf.new_from_file(self.get_file_path())
GLib.Error: gdk-pixbuf-error-quark: Impossible de reconnaître le format d'image du fichier « /home/romain/Images/3292.jpg » (3)
```

----

It's a very generic message: it's visible by default and hidden once the app has successfully started. Thanks for reporting it, i've no idea what's wrong with that image but i'll keep it to test the app

**Comment by LinuxOnTheDesktop** [comment]
My Firefox load it, but two image viewers would not. One of them, namely the default Mint image viewer (Xviewer 2.4.3), said this:

![image](https://user-images.githubusercontent.com/47056543/79199966-a845db80-7e2d-11ea-8298-43b996120121.png)

I think it possible that the website, or whomever supplies their images, built in some obfuscation.

**Comment by maoschanz** [comment]
no i understood the issue of that file, it's a webp image! it's a valid file, they just didn't rename it during the conversion

well, the mystery is solved but the issue is still not fixed:

- i have to show a better error message
  - [ ] in `image.py`, surround the line 160 with a try/except
    - [ ] in the except, change the message from the info banner and re-throw an exception
    - [ ] in the specific case of webp, instead of gdkpixbuf obscure message it should display a message useful to the user
  - [ ] in `main.py` some file handling errors are incorrectly catched as invalid flatpak commands
- distro maintainers should stop being clowns, even if [gnome doesn't want webp support in their code, the module for it exists](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/103) so they could at least package that module
