### ISSUE TITLE
On opening new tab canvas and background have same colour

### ISSUE THREAD

**Issue by avil25** [maoschanz/drawing#218]
## Description
on opening a new tab the canvas and background have the same color so it's hard to see where canvas ends. After opening the new tab old one also doesn't show the difference and after closing one of the tabs its show correctly. 
![Screenshot from 2020-04-26 20-50-03](https://user-images.githubusercontent.com/40562410/80311823-9423b600-87ff-11ea-8f35-1c7f0ac42849.png)

### Steps to reproduce the bug

1. open Drawing
2. open new tab

## System

- Device (desktop computer/tablet/phone/...):desktop computer
- OS: Ubuntu 20.04
- Desktop environment: Gnome
- Package format (flatpak, native package, snap?): native package
- App version: 0.4.13

Maybe adding a border or shadow at the end of the canvas is a good idea. (maybe I am silly enough 
to use the eraser on the empty canvas and they will be of the same color again)

**Comment by maoschanz** [comment]
yep i've never understood why it was doing that, it'll be fixed when i'll merge #213
