### ISSUE TITLE
Paste to selection is somewhat broken, should use different coordinates in a certain case

### ISSUE THREAD

**Issue by aerkiaga** [maoschanz/drawing#223]
## Description

Currently, if the user copies a selection, then pastes without deselecting, Drawing will paste right into the selection. This is not immediately obvious, or really useful. It should paste to the same location as when no selection is active.

Also, pasting to any selection in general can trigger illogical behavior, detailed in this bug report.

### Steps to reproduce the bug

1. Draw a rectangle
2. Draw a smaller circle further apart
3. Copy the circle
4. Deselect the circle
5. Select a portion of the rectangle
6. Paste the circle
7. Move the selection elsewhere
8. Deselect it
9. Undo
10. Deselect it again

The circle will magically jump to its former location, leaving the rectangle unchanged. This only happens upon deselection. Also, repeating steps 7 to 8 with any selection will duplicate it. This could be intended behavior, in which it is simply unexpected/non-discoverable.

## System

- Device (desktop computer/tablet/phone/...): desktop computer
- OS: Linux Mint 19.3
- Desktop environment: Cinnamon 4.4.8
- Package format (flatpak, native package, snap?): native package
- App version: 0.4.7

**Comment by aerkiaga** [comment]
Maybe I should split this into a bug report and an "other issue"...

**Comment by maoschanz** [comment]
Damn, selection from versions 0.4.x was so stupid...

The current behavior of the rectangle selection (from the unstable/development version, 0.5.3) is that:

* at step 6, the portion of the rectangle is unselected automatically, and the circle is pasted at coordinates (0, 0), which is not very usable so it is reported as #175, but it's still an improvement
* so from step 6 to 10 the rectangle is unchanged (but this time it's expected; in your case it's not)
* **at step 10 the circle still performs a wonderful but unexpected teleportation** > i let the issue open until this is fixed

If you try to make advanced montages you'll find dozens of other inconsistencies regarding interactions between the selection and the history, the version 0.4.x are far from good lol

**Comment by aerkiaga** [comment]
Okay, I'm sorry for reporting an older version, forgot to check... At least I'm relieved to see that the core issue still applies.

**Comment by maoschanz** [comment]
since commit d70eb43f32b253784cec26334b554bc469e07cc7 step 10 is fine but at step 9 the circle appears at coordinates (0, 0) 🤔
