### ISSUE TITLE
Moving/deleting selected area could leave secondary color instead of transparency

### ISSUE THREAD

**Issue by GabeAl** [maoschanz/drawing#232]
## Description

Opened this program for the very first time and tried to use it like MS Paint. I added some lines, then tried to move a portion of the image elsewhere. I clicked the "Selection" tool, dragged it around the portion to move, then while hold-clicking, tried to move it. It did move, but left a nasty gray square where the contents were moved. I tried changing foreground and background colors to anything -- no difference. Same happens when I try to delete using the Selection tool. Nasty gray takes the place of what I wanted to remove. 

Just to make sure I wasn't going crazy, I tried using the color picker to point to the white background to set both primary and secondary color to white. No success -- always gray is left behind. 

This seems like a pretty fundamental issue with the Selection tool. Am I the only one who has this problem? 

![image](https://user-images.githubusercontent.com/8050438/85237181-bf3b1800-b3f2-11ea-9ea4-a504b0b324f3.png)

Selecting a region:
![image](https://user-images.githubusercontent.com/8050438/85237188-cbbf7080-b3f2-11ea-90b7-8cd9bc852f85.png)

Moving it:
![image](https://user-images.githubusercontent.com/8050438/85237191-d7129c00-b3f2-11ea-9c60-73461329c715.png)

## System

- Device (desktop computer/tablet/phone/...): Desktop
- OS: Fedora 32
- Desktop environment: Gnome
- Package format (flatpak, native package, snap?): Gnome app store ("Software")
- App version: 0.4.13-1.fc32 (02/28/2020)

**Comment by maoschanz** [comment]
That's not grey, but pure transparency: in this aspect, it really differs from MS Paint

However i agree it should be an option

**Comment by GabeAl** [comment]
Thanks -- this makes sense. I didn't consider transparency. Agreed an
option would be good, like with other tools a bottom panel could allow for
selection of the background.

**Comment by maoschanz** [comment]
![Capture d’écran de 2020-12-14 01-46-30](https://user-images.githubusercontent.com/19996113/102029359-82068000-3dae-11eb-82a6-4f7b27447f98.png)

fixed 👍
