### ISSUE TITLE
Draw a shape using dashed outline

### ISSUE THREAD

**Issue by eggbrown** [maoschanz/drawing#233]
## Use case

I am working as a Technical Content Writer with a reputed US based organization. I use Drawings as my primary App because of its simple design and ease of use. I run in with images and screen shots very often, wherein I have to draw a border around an image. The Line feature in Drawings already has that.  

## Suggested solution

Since the Code is already there to draw an arrow or a line using dashes. It can be implemented for drawing a rectangle or a square or circle.

### Possible drawbacks

I don't suspect any new problems as the application is already in a stable state.

### Possible alternatives

Just to draw a dashed/dotted border I have to switch to and fro between GIMP and Drawing App. GIMP is no doubt a feature rich app, however it simply lacks the simplicity the Drawing app has. 
![Screenshot from 2020-07-08 16-41-56](https://user-images.githubusercontent.com/68009322/86912113-0850d300-c13a-11ea-8ee6-08ddc7f4ad0e.png)

**Comment by maoschanz** [comment]
i renamed the issue because the next version uses a single "shape" tool

i'll do this feature like this:
 ![Capture d’écran de 2020-07-08 13-57-47](https://user-images.githubusercontent.com/19996113/86915928-147d6600-c123-11ea-8b4d-472edd9d9af2.png)

**Comment by maoschanz** [comment]
![Capture d’écran de 2020-07-09 01-17-24](https://user-images.githubusercontent.com/19996113/86979987-f5162580-c182-11ea-9f2e-5c253e82f3b0.png)

no idea when it will be released

**Comment by eggbrown** [comment]
Hello Maochanz,

Apologies for the delay in response.
I am glad that my request was heard. I am happy to use the application as
my daily driver.
Let me know how can I buy you a coffee?

Mohammad Wasif

**Comment by maoschanz** [comment]
Hello,
There is a paypal link somewhere on the github page, but maybe wait for the
actual release of the feature in the upcoming version 0.6 to pay me a
coffee 😉

Thank you,
Romain T.
