### ISSUE TITLE
Selected image is zoomed

### ISSUE THREAD

**Issue by silocoder** [maoschanz/drawing#236]
Linux Mint 20
Cinnamon 4.6.6
Drawing 0.4.13
Resolution 2880x1620 laptop monitor

Why does this happen when I try to select an area? It seems to zoom the selection.

![image](https://user-images.githubusercontent.com/57298274/87956148-adde3d80-ca7c-11ea-98d5-463e13490609.png)

Original
![image](https://user-images.githubusercontent.com/57298274/87956596-3e1c8280-ca7d-11ea-9454-7a03ab3f5817.png)

**Comment by maoschanz** [comment]
yeah everything is completely bugged with HiDPI monitors, hard to fix it from my 1366×768 laptop

**Comment by maoschanz** [comment]
probably useful data so i can understand the problem:

![Capture d’écran de 2020-07-21 03-18-44](https://user-images.githubusercontent.com/19996113/88001770-37375380-cb01-11ea-955f-5e3acce5349b.png)

![](https://en.meming.world/images/en/thumb/9/91/Oof_Size_Large.jpg/300px-Oof_Size_Large.jpg)
