### ISSUE TITLE
Eraser Icon

### ISSUE THREAD

**Issue by vnikoofard** [maoschanz/drawing#252]
This isn't an issue. But I would like to know where is the Eraser Icon in the program. I couldn't find it. 

## System

- Device (desktop computer/tablet/phone/...): Laptop
- OS: Ubuntu 20.04.1
- Desktop environment:
- Package format (flatpak, native package, snap?): Native package manager
- App version: 0.4.10

**Comment by maoschanz** [comment]
this one? https://github.com/gnome-design-team/gnome-icons/blob/master/art-libre-symbolic/artlibre/scalable/tools/stock-tool-eraser-symbolic.svg

**Comment by vnikoofard** [comment]
Thanks for your attention. 
This is an image from all of the icons that I've on the left side of the window. The eraser icon isn't among them
https://drive.google.com/file/d/1sebQeIi03JWqV6VYZ0Ln26en36B9LpId/view?usp=sharing

**Comment by maoschanz** [comment]
Oh sorry, i thought you wanted the source of the icon, but actually you're looking for an "eraser" tool and this is a feature request

It has been implemented but it's not released yet.

**Comment by maoschanz** [comment]
duplicate of #149, where you can read how to achieve the behavior of an eraser using the normal pencil tool

**Comment by vnikoofard** [comment]
Ah, yes! Nice trick! Thanks for your kind attention
