### ISSUE TITLE
invert color

### ISSUE THREAD

**Issue by midnext** [maoschanz/drawing#255]
## Requested feature
invert color

### Possible alternatives
gnome-paint provides this function, but it lacks drawing in many respects

## Use case

this function allows you to very quickly process a screenshot of the cad (black background and white lines) to be able to insert it in email, brochure or presentations, saving a lot of toner in the printing phase.

thanks for what you can do

**Comment by maoschanz** [comment]
this is already implemented, it will be released with version 0.6

**Comment by midnext** [comment]
really thank you, I will gladly wait for the new version
