### ISSUE TITLE
How to contribute with a translation

### ISSUE THREAD

**Issue by ArthurBacci64** [maoschanz/drawing#261]
Bonjour

So, I added some translation to `pt_BR.po`, but I am so new in git and I don't now exactly how to contribute here. I readed the CONTRIBUTE.md file, but when I run `git push` after commiting, the server return 403:
```
Username for 'https://github.com': ArthurBacci64
Password for 'https://ArthurBacci64@github.com': 
remote: Permission to maoschanz/drawing.git denied to ArthurBacci64.
fatal: unable to access 'https://github.com/maoschanz/drawing.git/': The requested URL returned error: 403
```
Can someone ask me how to I do this correctly?

**Comment by maoschanz** [comment]
Sorry i know there are easier workflows for translators but i haven't take time to try them yet

in CONTRIBUTING.md, the first step is 

>Fork the repo and clone your fork on your disk

you were not supposed to clone my repo, but to fork it to your account, and clone this fork. On your fork, you'll have the permission to push any contribution you want.

Then github will provide a button to open a "pull request", so i can merge your version into mine

**Comment by ArthurBacci64** [comment]
Ok, thank you.
