### ISSUE TITLE
Improve fullscreen mode

### ISSUE THREAD

**Issue by NoorWachid** [maoschanz/drawing#265]
It would be great if this mode or layout added on fullscreen mode, especially for screencasting.

----

Edit:

- [x] implement #189 but keep an "exit fullscreen" simple action with dedicated shortcut
- [x] hide the menubar maybe
- [ ] a boolean "show tools" action that shows/hides both the side and bottom panes
  - [x] toggled by middle click with no movement IF THE WINDOW IS FULLSCREENED
  - [ ] toggled by kbd shortcut (+ menubar item)
- [x] current menubtn for the fullscreen menu moves at the end of the bottom pane and directly exits the fullscreen mode

**Comment by maoschanz** [comment]
not sure if it's what you're asking for, but a fullscreen mode has been developed (#91 #244 etc.), it's not released yet, here is a screenshot:

![Capture d’écran de 2020-09-16 15-35-58](https://user-images.githubusercontent.com/19996113/93344899-82848e80-f832-11ea-83da-69509f17ad86.png)

**Comment by maoschanz** [comment]
unless you tell if it's what you were asking, i'll close the issue

**Comment by NoorWachid** [comment]
For example in Krita when I pressed `Tab` it goes to fullscreen-mode with notools, nocolorpallets etc. They only triggered by right click. https://imgur.com/gallery/tvZwP63

**Comment by maoschanz** [comment]
I see, but here both the right click and the middle click already have several features attached to them, so it can't behave like Krita.

i'll edit your comment to add my little checklist of things to do (github only understands these lists when they're in the 1st comment)
