### ISSUE TITLE
Where are the config files

### ISSUE THREAD

**Issue by soystemd** [maoschanz/drawing#266]
# Question
Where are drawing's [user-specific] config files stored?
In case I want to remove all the config files and start fresh, or just uninstall the package and remove any leftover config files.
## System

- Device: Desktop
- OS: Artix/Arch linux
- Package : Arch community package (https://www.archlinux.org/packages/community/any/drawing/)
- App version: 0.4.13

**Comment by maoschanz** [comment]
it uses the GSettings abstraction provided by GNOME libs

```bash
gsettings reset-recursively com.github.maoschanz.drawing
```
or `gsettings reset com.github.maoschanz.drawing [press tab twice to get the list of individual existing keys]`

internally, GSettings can work with a plain text config files backend but it's more efficient to use the Dconf backend so it's usually packaged to use that: there is a database at `~/.config/dconf/user`, that can be browsed using the `dconf` command line or the `dconf-editor` app

**Comment by soystemd** [comment]
Ah I see, thanks for the detailed answer.
I expected something like a .drawingrc file somewhere and I was going crazy when I couldn't find it.
Closing.

**Comment by maoschanz** [comment]
What i told is true for the native packages, but i realize it's wrong for flatpak: dconf isn't accessible from within the sandbox, so it's an actual config file, at `~/.var/app/com.github.maoschanz.drawing/config/glib-2.0/settings/keyfile`
