### ISSUE TITLE
Add (unofficial) Gentoo package

### ISSUE THREAD

**Issue by TheEvilSkeleton** [maoschanz/drawing#272]
Hello, we have created a Gentoo package in our overlay. Feel free to include them in your Packaging status:

https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/master/media-gfx/drawing

**Comment by maoschanz** [comment]
it's not covered by repology.org because it's an unofficial package?

**Comment by TheEvilSkeleton** [comment]
Correct, it's from an external Gentoo overlay (think of Ubuntu's PPA but for Gentoo), so it's an external repository containing packages.
