### ISSUE TITLE
Add URL to "Report-Msgid-Bugs-To" in pot/po header

### ISSUE THREAD

**Issue by scootergrisen** [maoschanz/drawing#279]
Suggest adding an URL to the pot/po files header:

From:

    "Report-Msgid-Bugs-To: \n"

To:

    "Report-Msgid-Bugs-To: https://github.com/maoschanz/drawing/issues\n"

**Comment by maoschanz** [comment]
I've never been able to add it because it's erased each time i re-generate the files with ninja. If you know how to do, the url would be `https://github.com/maoschanz/drawing/issues/new/choose` instead.

**Comment by scootergrisen** [comment]
I don't know anything about ninja.
Seems other software i translate just link to the main issue page and not the one specific to creating a new issue but of course you can link to anything you like.

**Comment by fossfreedom** [comment]
@maoschanz should be able to set via meson.build - i.e. the "--msgid-bugs-address" https://github.com/iptux-src/iptux/blob/master/po/meson.build

**Comment by maoschanz** [comment]
thank you, i'll try this

**Comment by scootergrisen** [comment]
I suggest using the url first suggested without the new at the end.

**Comment by scootergrisen** [comment]
If you use https://github.com/iptux-src/iptux/issues/new and the user is not signed in the user will not see the issue page.
And it might be a good idea for the user to see if the issue already exists.

**Comment by maoschanz** [comment]
i'm fine with duplicates
