### ISSUE TITLE
Crop to Selection

### ISSUE THREAD

**Issue by ericvoid** [maoschanz/drawing#283]
## Use case

The current "Crop" tool isn't very intuitive, and it could be replaced by a simpler "Crop to Selection" feature.

Currently, on Ubuntu (20.04) Desktop the "Crop" tool doesn't work very well.

## Suggested solution

The "Selection" tool could have a "Crop" option in the bottom bar, so the workflow would be:

1. select "Selection" tool;
2. select a rectangular area on the image;
3. click on "Crop" on the bottom bar.

![image](https://user-images.githubusercontent.com/2678015/96198186-7d4a5a80-0f2a-11eb-979a-e31361595b6b.png)

### Possible drawbacks

This wouldn't replace the "Crop" tool, since it may work better on touch screens. The "Crop to Selection" would suit better when using mouse or touch pad.

**Comment by ericvoid** [comment]
I just installed the newer version from PPA, and I noticed there are many improvements on v. 0.6.

I think this enhancement request may be deprecated.

**Comment by maoschanz** [comment]
i also think it's deprecated

the crop tool can still be improved (#85 ) but i'll close this issue because the crop tool is used to expand the size of the canvas, and it would be impossible with the suggested solution

**Comment by maoschanz** [comment]
i'll do it but it'll not be as prominent as you suggested, and it'll not replace the crop tool: #332
