### ISSUE TITLE
[Line tool] Visual glitch with "arrow" and "square" options set

### ISSUE THREAD

**Issue by Staudey** [maoschanz/drawing#285]
## Description

Using the line tool with the "arrow" option and the line set to "square" the corners of the square line are extending beyond the arrow tip, see screenshot below.
![arrow_error](https://user-images.githubusercontent.com/6317346/96350737-67b66b80-10b7-11eb-92fe-cc8f001ff455.png)

### Steps to reproduce the bug

1. Select the line tool
2. Select "Square" as the line shape
3. Select the "Arrow" option
4. Paint a few arrows and look at the tips of the arrows

## System

- Device (desktop computer/tablet/phone/...): Desktop computer
- OS: Solus 4.1
- Desktop environment: Budgie 10.5.1
- Package format (flatpak, native package, snap?): native package
- App version: 0.6.2

**Comment by maoschanz** [comment]
meanwhile if you want arrows with a square end, just select "thin" instead of "square", as long as the line isn't dashed it's the same
