### ISSUE TITLE
How can I zoom out?

### ISSUE THREAD

**Issue by dpinol** [maoschanz/drawing#294]
How can I zoom out the image?
I tried +/- with/out control, and I didn't find any menu option

thanks

## System

- Device : dell xps 13 laptop
- OS: Linux Mint 20 Ulyana
- Desktop environment: cinnamon
- Package format (flatpak, native package, snap?):
- App version: 0.4.13

**Comment by maoschanz** [comment]
This feature didn't exist with the 0.4.x versions. To get the zoom, install the version 0.6.2, from Flathub or from the PPA
