### ISSUE TITLE
Add a way to change the active tool using keyboard

### ISSUE THREAD

**Issue by kiraleos** [maoschanz/drawing#300]
## Requested feature

Right now keyboard shortcuts are rarely used. I think a good addition would be to add shortcuts for common tasks and tools like Pencil, Eraser, Text and Rectangular Selection, along with a shortcut to increase/decrease the brush size.

Those shortcuts could be: 'B' or 'P' for Brush/Pencil, 'E' for Eraser, 'T' for text, 'S' for selection and '=' and '-' for increasing/decreasing the brush size.

### Possible drawbacks

Not any that I can think of, the aforementioned shortcuts don't conflict with any existing ones.

## Use case

Keyboard shortcuts are always handy. In a program like Drawing, one can draw with one hand, and the other hand presses the shortcuts to change tools etc. without moving one hand from the mouse to the keyboard.

**Comment by maoschanz** [comment]
>keyboard shortcuts are rarely used

Saving? Creating a new tab? Undoing? Copying? Pasting? Zooming in or out? The shortcuts window currently has 4 pages of shortcuts. The last stable version has "only" 3 entire pages but they're quite overcrowded...

>common tasks and tools like Pencil, Eraser, Text and Rectangular Selection

This is highly subjective, i wouldn't consider "Eraser" to be common at all. This tool isn't even enabled by default.

>along with a shortcut to increase/decrease the brush size.

it was reported as #242 and it's fixed

>Those shortcuts could be: 'B' or 'P' for Brush/Pencil, 'E' for Eraser, 'T' for text, 'S' for selection and '=' and '-' for increasing/decreasing the brush size.

All of them conflict with existing ones except P (and = but increasing size already exists and it's shift+ctrl+↑)

----

Anyway, if a shortcut is too complex to remember or to type, people will just not type it. So to have something consistent across tools, and less english-centric, I think the solution is too use underscore accelerators, but i'm not sure how well it works when the label can be hidden from the button.

Also, it relies heavily on the quality of translations, and putting that in place would require to remove this feature from the menubar for people currently using it

**Comment by jn64** [comment]
I suggest using number keys 1 to 0, corresponding to the enabled tools (not fixed mappings).

- Language agnostic, doesn't require translations.
- Doesn't require any decisions about which key maps to what tool.
- Doesn't require learning or memorisation.

Of course, the limitation is only the first 10 tools will have shortcut keys.

Another idea is to use a modifier key with scrollwheel to change tools.
