### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by tim77** [maoschanz/drawing#31]
#### Not issue, just info:

📦 Drawing RPM package in [COPR](https://copr.fedorainfracloud.org/coprs/atim/drawing/)

How to install:
```shell
sudo dnf copr enable atim/drawing -y && sudo dnf install drawing -y
```
Run:
```
drawing
```

**Comment by maoschanz** [comment]
i'll add it in the readme

**Comment by tim77** [comment]
If you wish. 😊 I am trying to push this app into official Fedora repos. Its great IMO. Thank you for this app.

**Comment by tim77** [comment]
Now in official Fedora repos and ready for testing:

[Fedora 29](https://bodhi.fedoraproject.org/updates/drawing-0.2-1.fc29)
[Fedora 30](https://bodhi.fedoraproject.org/updates/FEDORA-2019-2478ff3440)

**Comment by TeknoMobil** [comment]
Thanks, good news, what's the status?

**Comment by TeknoMobil** [comment]
Gnome application does not appear in the center
Installing with dnf: sudo dnf install drawing

Thanks

**Comment by tim77** [comment]
> Gnome application does not appear in the center
Appstream data package updates periodically, once per two weeks approximately. Probably just need to wait a little bit.

**Comment by TeknoMobil** [comment]
Yes now appears in the app market

> > Gnome application does not appear in the center
> 
> Appstream data package updates periodically, once per two weeks approximately. Probably just need to wait a little bit.

Yes now appears in the app market

**Comment by ForlornWongraven** [comment]
Looking forward to another release so Fedora can push another update in the official repo.

**Comment by maoschanz** [comment]
i think i can close this one
