### ISSUE TITLE
Amazing software, many thanks!!

### ISSUE THREAD

**Issue by dxnacho** [maoschanz/drawing#32]
Thank you so much for your work, I was looking for something like this since Shutter is no longer in repositories (so difficult to install).
I believe this program has the potential to be the new screenshots editor (and more) for GNOME desktop. I'm just missing some features, which imo will improve the user experience (in no particular order):
- Being able to select an object that you previosly drawed (I understand this could be difficult even maybe not possible)
- Have an option to add shades in the objects?
- Add arrows (one or two way)
- Turn circle into ellipse (by pressing shift or ctrl still be able to do a perfect circle)
- Add "blur" option
- Add "numbers" option (*)

(*) this and other ideas were taken from [Ksnip](https://github.com/DamirPorobic/ksnip) which is already a great opensource project, but not (so) suitable for GNOME desktops.

Many thanks again for all the effort!!

**Comment by maoschanz** [comment]
>Being able to select an object that you previously drawed (I understand this could be difficult even maybe not possible)

It is possible, and not even difficult for most tools, i think i'll do it

>Have an option to add shades in the objects?

This one is harder

>Add arrows (one or two way)

One-way arrow are already possible, as an option of the "line" tool and the "arc" tool.

>Turn circle into ellipse (by pressing shift or ctrl still be able to do a perfect circle)

I admit my current ellipses look like potatoes 😅

>Add "blur" option

Good idea, but i've no idea how hard it is

>Add "numbers" option (*)

Could you explain this one?

**Comment by dxnacho** [comment]
> Could you explain this one?

Explained in this picture:

![image](https://user-images.githubusercontent.com/28144115/55888022-ef601780-5bae-11e9-8452-c1b7a4426fc6.png)

As I said, Ksnip is providing that features, they're just a few things, but very interesting ones :)

Very happy to have found this project :)

**Comment by maoschanz** [comment]
I close this one to keep few opened issues, but your ideas are all in #21
