### ISSUE TITLE
Some font settings aren't saved on exit

### ISSUE THREAD

**Issue by flyingpimonster** [maoschanz/drawing#340]
## Description
When you close and reopen Drawing, the font selection is saved, but not the other font settings.

### Steps to reproduce the bug

1. Open Drawing.
2. Select a new font, select bold and italic, and change the font background type.
3. Close and reopen Drawing.
4. The new font is still selected, but bold, italic, and background type are reset to defaults.

## System

- Device (desktop computer/tablet/phone/...): Desktop
- OS: Fedora 33
- Desktop environment: GNOME
- Package format (flatpak, native package, snap?): Flatpak
- App version: 0.6.5

**Comment by maoschanz** [comment]
that's not a bug, these settings aren't supposed to be saved

There are far too much options, i can't save them all, the saved ones are [those ones](https://github.com/maoschanz/drawing/blob/master/data/com.github.maoschanz.drawing.gschema.xml#L101) only, though i think i'll add the shape filling style and the colour application mode to this list
