### ISSUE TITLE
Current font isn't pre-selected in the font chooser dialog

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#359]
## Description

Current font isn't pre-selected in the font chooser dialog

(also, fix the TODO in the option manager regarding the font name)

### Steps to reproduce the bug

1. Select a font X
2. Confirm
3. Select a font again → the pre-selected one isn't the font X

## System

- Package format: flatpak
- App version: 0.8.0

**Comment by Abdallah-Moh** [comment]
font_chooser.set_font ("font_family");

**Comment by maoschanz** [comment]
it's already what's in the code 

https://github.com/maoschanz/drawing/blob/master/src/tools/classic_tools/tool_text.py#L59

the issue isn't a feature request, it's labelled "bug" because it's already implemented but it doesn't work as excepted
