### ISSUE TITLE
Hebrew Translation

### ISSUE THREAD

**Issue by moriel5** [maoschanz/drawing#36]
If it alright with you, I'd like to help translate Drawing to Hebrew.
In the meantime, I am starting on the translation.

Additionally, I had posted a package request for Drawing (when it reaches 1.0) in the Solus Phabricator.

**Comment by maoschanz** [comment]
No problem, you can translate it in Hebrew, but if it's possible test your translation and report issues here (if there are problems), because i've no idea how the labels would look like with an RtL writing system

>when it reaches 1.0

My version numbers are quite meaningless, i fix/improve/add things and when it looks stable i increment, release it on flathub, and increment again

**Comment by moriel5** [comment]
Thanks, I'll test it on my sister's laptop (I had installed it there in any case), since my PCs are in english, and I don't want to keep changing the language there.

As to versioning, I was told that when Drawing drops the "Beta" tag, and officially becomes "stable", it can be decided upon whether it will be added to the Solus repositories.

Currently I have 10 strings left to translate (I am having trouble translating the word "canvas", as well as a few other words), so I hope to be able to issue a pull request within the next few days.

**Comment by moriel5** [comment]
I am having issues translating "canvas" and "legacy".
I think the literal translation for "canvas" should work? It is the same word for "fabric".

**Comment by moriel5** [comment]
Alright, for the time being, I'm translating "legacy" to "previous".

**Comment by moriel5** [comment]
Everything seems to be alright now, and RTL seems to be working perfectly here.
May I send a pull request?

**Comment by maoschanz** [comment]
To be honest i'm not a native english speaker, i use "canvas" because it's how GIMP says it, but it might not be the best word

Concerning "legacy", it's in the preferences, it describes the window layout with a menubar and a toolbar. In french i translated it as "Traditionnelle" ("traditional")

**Comment by maoschanz** [comment]
And yes you can send a pull request

**Comment by maoschanz** [comment]
Concerning the "beta" tag, i let it in the github repo description because what is here is of course unstable, but in fact when i release something with an even version number in the "Releases" tab it can be considered as a stable version

**Comment by moriel5** [comment]
Thanks. It appears that in GIMP they translate it to roughly "the drawing pad", so I'll do that as well.
And thank you very much, the translation for "traditional" does fit in much better.
As for the versioning, I'll notify over on the Solus Phabricator after I update the translation.

**Comment by maoschanz** [comment]
the 0.2 version is stable but has a lot of bugs, i suggest to wait the 0.4

**Comment by moriel5** [comment]
Thanks for telling me.
Does that mean that the in-development 0.3 version will be 0.4 upon marking as stable?

**Comment by maoschanz** [comment]
yes, i can let the issue open until the 0.4 release and tell you about it then

**Comment by moriel5** [comment]
Don't worry, you can close this issue once my pull request is merged.
I am keeping tabs on here in any case.

**Comment by moriel5** [comment]
I have made a pull request now.

**Comment by maoschanz** [comment]
The version 0.4.2 is released

**Comment by moriel5** [comment]
Thanks, I'll get to it.
By the way, I'm trying to get Drawing to officially enter the Solus Repos, so it will simply be `sudo eopkg it drawing`, or just install Drawing from the Solus Software Center.
