### ISSUE TITLE
drawing -c not working with Wayland

### ISSUE THREAD

**Issue by Faustop** [maoschanz/drawing#377]
## Description

Launching drawing with the `--edit-clipboard` option doesn't work, the application launches but doesn't open the clipboard image. Instead it displays the error message "The clipboard doesn't contain any image."

Note that subsequently clicking "New image from clipboard" on the menu does work, so it proves that the clipboard actually contains an image.

### Steps to reproduce the bug

1. Copy an image to the clipboard on other application
2. launch Drawing with the `--edit-clipboard` option, or from the app icon's menu item "Edit clipboard content"
3. It doesn't work.
3. (extra step) click "Paste" (that will work, proving there is an image in the clipboard)

## System

- Device (desktop computer/tablet/phone/...): Laptop computer
- OS: Arch Linux
- Desktop environment: Gnome with Wayland
- Package format: native from community repository 
- App version: 0.8.0

**Comment by maoschanz** [comment]
it works with the app installed as flatpak, i'll try tomorrow with a native package

also, maybe it's a matter of wayland or xorg? which one are you using?

**Comment by maoschanz** [comment]
ok it looks like Wayland: on Debian Sid the option `-c` is broken with wayland

**Comment by maoschanz** [comment]
the fix i tried works but

like

only sometimes?

i let the issue opened but i suppose fewer people will encounter the problem in the future=
