### ISSUE TITLE
Eraser doesn't remove pixel color, it makes them black

### ISSUE THREAD

**Issue by ngharrison** [maoschanz/drawing#379]
## Description

When I try to erase anything, it's as if it is drawing still (in black). If I select a rectangle and then delete, it turns that rectangle black as well.

Screenshot showing a deleted rectangle and an eraser mark:
![image](https://user-images.githubusercontent.com/7918794/118549654-02902a80-b719-11eb-99fc-ea66da5d1a20.png)

### Steps to reproduce the bug

1. Open app
2. Draw anything
3. Select Eraser or Rectangle selection
4. Draw to erase or select rectangle and hit delete

## System

- Device (desktop computer/tablet/phone/...): laptop
- OS: Linux Mint
- Desktop environment: Cinammon
- Package format: From repo (ppa:cartes/drawing)
- App version: 0.8.0

**Comment by maoschanz** [comment]
may i have a screenshot of the app running on your system?

**Comment by ngharrison** [comment]
Yes, I should have included that. I've updated my original post.

**Comment by ngharrison** [comment]
And I believe I've figured out my own problem. I didn't realize erasing was replacing the color with a "Transparency", not the image background color. I switched the eraser and selection options to replace with the "Default color" instead.

**Comment by maoschanz** [comment]
that's what i suspected, you're not the first one to have this problem

in the 3rd page of the preferences, you can set a more flashy background color behind the canvas if you prefer, this way you'll not be confused again
