### ISSUE TITLE
when open an image also opens a tab with an 'Unsaved File'

### ISSUE THREAD

**Issue by muydipalma** [maoschanz/drawing#390]
hi! nice app! very lightweitgh! i have an issue, not very important but i wonder if i can fix it in anyway:

when open an image also opens a tab with an 'Unsaved File' , im using openbox in arch, tried to do it from terminal and still opens an "unsaved file" tab alonside the image i want to edit

## System

- Device (desktop computer/tablet/phone/...): computer
- OS: arch linux
- Desktop environment: openbox
- Package format: yay 
- App version: 0.8.0

**Comment by muydipalma** [comment]
Both of them, when i open from command line any image i recieve this message:

```
$ drawing Screenshot_2021-06-08-12-53-44_3840x1080.png
Error opening this file. /usr/bin/drawing isn't an image.
```

**Comment by maoschanz** [comment]
i think it's because of the package format, i haven't tested outside of a flatpak sandbox for a long time

**Comment by maoschanz** [comment]
I fixed it but i can't push the fix because github is pure shit. Time to migrate on gitlab.

**Comment by maoschanz** [comment]
nevermind it's just completely dumb i have to generate tokens and keep them as clear text on my disk so i could copy-paste them instead of my true password (??????)

I'll migrate on gitlab later i suppose
