### ISSUE TITLE
Crash when initializing the "Tools" menubar's menu (Ubuntu 21.04)

### ISSUE THREAD

**Issue by tomaswarynyca** [maoschanz/drawing#403]
## Description
When trying to run the programme, it closes

`/usr/share/drawing/drawing/window.py:477: Warning: g_hash_table_ref: assertion 'hash_table != NULL' failed
  current_item = current_item.get_item_link(item[1], link_type)
**
GLib-GIO:ERROR:../../../gio/gmenumodel.c:401:g_menu_model_real_get_item_link: code should not be reached
Bail out! GLib-GIO:ERROR:../../../gio/gmenumodel.c:401:g_menu_model_real_get_item_link: code should not be reached
[1]    15132 IOT instruction (core dumped)  drawing`

### Steps to reproduce the bug

1. Execute drawing in the terminal

## System

- Device (desktop computer/tablet/phone/...): laptop
- OS: Ubuntu 21.04
- Desktop environment: Gnome
- Package format: PPA
- App version: 0.8.2-0ubuntu1~hirsute

**Comment by tomaswarynyca** [comment]
The latest update solved the problem, great! 👍🏻

**Comment by maoschanz** [comment]
not sure why 😅
