### ISSUE TITLE
Support webp?

### ISSUE THREAD

**Issue by luismidelgado** [maoschanz/drawing#424]
## Requested feature

There are plans to be able to edit webp files in the future?

## Use case

Thank you for this great application

**Comment by maoschanz** [comment]
this app doesn't support specific image formats, it relies on GdkPixpuf

To add webp support to the GdkPixbuf library , you may install or compile this https://github.com/aruiz/webp-pixbuf-loader on your system, or [ask gdk-pixbuf maintainers instead](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues) (they already said no but they're wrong imho)

**Comment by oumout** [comment]
what do you think about "exporting as avif"?
