### ISSUE TITLE
undo function is extremely slow

### ISSUE THREAD

**Issue by tethragon** [maoschanz/drawing#435]
## Description

When I draw many handwritten notes (letters, numbers, lines etc.), then the undo function is extremely slow.

### Steps to reproduce the bug

1.open drawing
2. draw with pencil tool letters, digits, lines etc.
3. try undo

## System

- Device (desktop computer/tablet/phone/...): desktop computer
- OS: Linux Mint 20.2
- Desktop environment: Cinnamon 
- Package format-->: native package from the distribution repository
- App version: 0.8.0

**Comment by maoschanz** [comment]
You're supposed to check whether the issue is already reported or not *before* opening it
