### ISSUE TITLE
Display coordinates and line length

### ISSUE THREAD

**Issue by vanillajonathan** [maoschanz/drawing#439]
## Requested feature
I want the application to display the X and Y positions of the mouse cursor over the drawing canvas. I also want it to display the W (width) and H (height) when drawing a line.

### Possible drawbacks
No.

### Possible alternatives
None,

## Use case
Make it easier to draw straight lines and do technical drawing.
Example, I want it to draw a line from 10, 10 (X, Y) and want the line to be 100 pixels wide and end at position Y 10.

**Comment by maoschanz** [comment]
concerning x and y, that's a plan i've had for a very long time but for now i have no idea where to display this information

concerning the width and height, it's unlikely i do it, it would be quite complex to maintain this for each tool

**Comment by vanillajonathan** [comment]
Other software such as GIMP and MS Paint display the coordinates in a status bar at the bottom of the window.

The width and height is mostly interesting for lines and rectangles. Not so much for the other tools, although the circle could display radius.

**Comment by maoschanz** [comment]
I've already seen Paint thanks, it doesn't change the fact that the bottom of my window is full.

**Comment by vanillajonathan** [comment]
![image](https://user-images.githubusercontent.com/10222521/139713585-b4adbd53-8674-48ea-9f4c-b07364ddeaa6.png)

**Comment by maoschanz** [comment]
Thank you for this helpful tip, as you can guess i had never seen this area before

**Comment by vanillajonathan** [comment]
Please add coordinates!
GTK also offers a [`GtkOverlay`](https://docs.gtk.org/gtk4/class.Overlay.html) widget that could be used so you can overlay it over the canvas if there is no space available in the bottom toolbar / statusbar.

**Comment by maoschanz** [comment]
If the issue is still open and i say things like "that's a plan i've had for a very long time", it means it'll happen, i just have no idea when and how.

**Comment by vanillajonathan** [comment]
Thank you, I look forward to it with great anticipation! 😆

**Comment by maoschanz** [comment]
no more need to find available space if i don't display it unless the user presses <kbd>Ctrl</kbd>

![image](https://user-images.githubusercontent.com/19996113/140632250-e6fdc5fb-be38-45b0-b8fd-b6abe0a95c6b.png)

**Comment by vanillajonathan** [comment]
This is a bit different than I envisioned it, but this provides the requested functionality!

I think this will greatly improve Drawing, especially in conjunction with a grid and snap-to-grid functionality.
