### ISSUE TITLE
can't download the flathub version of your app

### ISSUE THREAD

**Issue by YousefSaber** [maoschanz/drawing#447]
```
(base) [josephsaber@fedora Downloads]$ flatpak install com.github.maoschanz.drawing.flatpakref
error: No entry for app/com.github.maoschanz.drawing/x86_64/stable in remote 'flathub' summary flatpak cache 
```

**Comment by maoschanz** [comment]
isn't it

```
flatpak install flathub com.github.maoschanz.drawing
```

?

**Comment by YousefSaber** [comment]
@maoschanz this doesn't also work 
```
(base) [josephsaber@fedora ~]$ flatpak install flathub com.github.maoschanz.drawing
Looking for matches…
error: Nothing matches com.github.maoschanz.drawing in remote flathub
```

and yeah 
```
com.github.maoschanz.drawing.flatpakref
``` 
was in the working directory of the terminal I tried to download it manually because the other method didn't work.

**Comment by maoschanz** [comment]
This is very strange, do other flathub apps work?

**Comment by YousefSaber** [comment]
@maoschanz I'm sorry it was my fault😓, I did what you said other apps didn't install correctly, initially I thought that Flatpak is enabled by default on Fedora but then it turns out that I had to [manually](https://flatpak.org/setup/Fedora/) enable it and yeah installation was smooth and fine.
