### ISSUE TITLE
Key+mouse combinaisons

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#46]
## Image-wide zoom management

- [x] ctrl+scroll = zoom

## Handle #439 and #98 

- [x] ctrl+hover = show tooltip as long as ctrl is pressed (in bold)
- [x] ctrl+click = show tooltip as long as the click isn't released (both bold and italic)

the tooltip has **the coordinates** in it, as well as tool-specific data:

- [x] color picker, color selection: **help label for colorblind users**
- [x] line, ~~curve~~: _delta x and y_
- [x] ellipsis, rectangle, rounded rectangle, rectangle selection: _width, height_
- [x] circle: _radius_

----

## Alternative tools behavior

This is totally impossible to guess for the user, but i don't care it's already available normally in menus

However:

- [ ] change the window subtitle as soon as a defined modifier is pressed

### Selection

- ~~[ ] shift = add to the selection~~ #449 
- ~~[ ] alt = substract from the selection~~ #449 

### Classic tools

- line
  - [x] shift = invert orthogonal lock
  - [x] alt = invert outline
- pencil, curve:
  - [x] alt = invert outline
- eraser
  - [x] shift = invert mode
- highlighter
  - [x] shift = invert mode
- shape
  - [x] shift = empty
  - [x] alt = main color
  - [x] shift+alt = secondary color

### Transform tools

- crop:
  - [x] shift = alpha
  - [x] alt = default color
  - [x] shift+alt = secondary color
- scale:
  - [x] shift = invert proportions locking
- rotate
  - [x] shift = flip (left click = horizontally; right click = vertically)
- skew: 
  - [x] shift = alpha
  - [ ] alt = default color
  - [x] shift+alt = secondary color

**Comment by Imerion** [comment]
Hi! I'm new here, but I've been following this fantastic project for a while and have been impressed with its polish and usability. Really nice work!

May I suggest a feature/option, regarding this? To have zoom as default option for mouse wheel, without the need for an extra button. (Or an option to set that behaviour). That would put it in line with most other drawing/painting apps such as Krita, not to mention other creative tools such as Blender, Godot, etc. I usually prefer to work using mouse wheel to zoom in and out and quickly change which part I am working on by zooming in where I need to be and then do small viewpoint adjustments with pan using middle-click. This works excellent in GIMP, Inkscape, etc which as options for it, or in the ones mentioned above where it is default.

Either way, thanks for working on this! :D

**Comment by maoschanz** [comment]
Krita is a very advanced app, i don't want to compete with it 😅

>To have zoom as default option for mouse wheel, without the need for an extra button.

I'm not sure, it doesn't look like a good idea...

Your suggestion makes sense for a mouse user, but as a touchpad user it feels absurd when apps zoom when i scroll. Apps doing this (maps viewers, image viewers, etc.) are often relying on an other mecanism to move: i had to dust off my old mouse to see what you meant concerning Krita, because it's not possible at all with a touchpad, i didn't even know this feature existed. I can implement this behaviour for the middle click regardless of how the zoom will work

>(Or an option to set that behaviour)

The ugliest but easiest solution, i'll probably do it like this

**Comment by Imerion** [comment]
> Your suggestion makes sense for a mouse user, but as a touchpad user it feels absurd when apps zoom when i scroll. Apps doing this (maps viewers, image viewers, etc.) are often relying on an other mecanism to move: i had to dust off my old mouse to see what you meant concerning Krita, because it's not possible at all with a touchpad, i didn't even know this feature existed. I can implement this behaviour for the middle click regardless of how the zoom will work

I guess it is because I use the classic "edge scrolling" on my touchpad. Middle-click works well on touchpad too since I have separate buttons. Most of the time I work with my mouse though. :) Awesome about the middle-click pan! :D

> The ugliest but easiest solution, i'll probably do it like this

Thanks! It's really, really appreciated!
