### ISSUE TITLE
Drawing 0.8.0 has a strange bug involving "Define as current image".

### ISSUE THREAD

**Issue by namelessandforsaken** [maoschanz/drawing#460]
## Description

The color picker in the in-build Drawing app breaks when you paste an image in and select "Define as current image".

![image](https://user-images.githubusercontent.com/95661684/144943002-b50a7900-6839-4b52-964a-47e3d4a642c4.png)

### Steps to reproduce the bug

1. Copy an image (easiest way is to do a screenshot of the screen and copy to the clipboard) and paste it into Drawing.
2. Select "Define as current image".
3. Color picker (and other tools) doesn't work unless you do hackish things.

## System

- Device (desktop computer/tablet/phone/...): HP Laptop
- OS: Linux Mint 20.2
- Desktop environment: Cinnamon
- Package format: Native package - built into Mint 20.2
- App version: 0.8.0

**Comment by maoschanz** [comment]
it is still a problem in 0.8.5, although the code is very different

the trace i got in the terminal is

```
Traceback (most recent call last):
  File "/app/share/drawing/drawing/image.py", line 508, in on_release_on_area
    self.active_tool().on_release_on_area(event, self.surface, event_x, event_y)
  File "/app/share/drawing/drawing/tool_picker.py", line 45, in on_release_on_area
    color = utilities_gdk_rgba_from_xy(surface, event_x, event_y)
  File "/app/share/drawing/drawing/utilities_colors.py", line 62, in utilities_gdk_rgba_from_xy
    rgba_vals[3] /= 255 # alpha has to be between 0 and 1
IndexError: list index out of range
```

i would be interested to see the error trace in your case

**Comment by maoschanz** [comment]
>i would be interested to see the error trace in your case

please?
