### ISSUE TITLE
Drawing horizontal straight line

### ISSUE THREAD

**Issue by alex-tw-lam** [maoschanz/drawing#462]
## Requested feature
To draw a horizontal straight line by holding the shift key. 

### Possible drawbacks
no

### Possible alternatives
Snapping the line to a horizontal angle would work just as well. 

## Use case
Draw a line under some text in an image. It would be nice if the highlight tool could draw straight lines.

**Comment by maoschanz** [comment]
Duplicate of both #46 and #369

The orientation locking is already here since the version 0.8.2 as a regular option of the "line" tool
