### ISSUE TITLE
Broken 'what's new' in help.

### ISSUE THREAD

**Issue by luciph0r** [maoschanz/drawing#474]
## Description

Ironic that after launching the updated version on Mint 20.3, it asks whether I want to see what's new in this release, then pops up a help window with a broken link. 
![image](https://user-images.githubusercontent.com/44374321/149055563-d4083fa3-c6a8-4220-8f8c-60080851cb80.png)

### Steps to reproduce the bug

1. Click on Help->What's new.

## System

- Device (desktop computer/tablet/phone/...): **Laptop**
- OS: **Mint 20.3**
- Desktop environment: **XFCE**
- Package format: **Official mint repos.**
- App version: **0.8.4**

**Comment by maoschanz** [comment]
if you open the help normally (by clicking on "help" or pressing F1):

- does the index page work?
- is the "what's new" page listed at the bottom of the index?

**Comment by luciph0r** [comment]
No, it doesn't work, and reports that `The URI ‘help:drawing/index’ does not point to a valid page.`

**Comment by luciph0r** [comment]
Thanks, removing localepurge and reinstalling fixed it.

**Comment by maoschanz** [comment]
great news, i don't know what i would have done otherwise lol
