### ISSUE TITLE
Points function - Dots too small for 2-digit and larger numbers

### ISSUE THREAD

**Issue by jbergengh** [maoschanz/drawing#477]
## Use case
When using the **Points** function, with **Dots Type** set to **Circle** or **Square**, and **Include a Number** selected, the dots are too small to contain a 2-digit or 3-digit number.  See example below.

## Suggested solution
Center the number text and enlarge the dot Circle or Square so the number text fits within it.

### Possible drawbacks
Possible drawbacks might be differing size Dots and Squares.  If this is an issue, go with a standard Dot/Square size big enough to fit 2-digit numbers, which should be adequate for nearly all cases.

![Untitled](https://user-images.githubusercontent.com/55407804/149975155-c2e08116-fddd-4e51-9863-0a79835e96b2.png)

**Comment by jbergengh** [comment]
@maoschanz My job involves creating dozens and dozens of diagrams like the one I've posted below, where I have to enter page numbers in my Page Arrangement diagrams.  I was using the **text** tool, typing each and every page number in one at a time.  It was very time consuming, but then I discovered the **Points** tool with the **Include a Number** feature that incremented with each point.  OMG what a lifesaver!  This has saved me countless hours of time.  Now one click per page does the job.

There are two things that would make the points function perfect for me.

1) The circle and square dots type does a good job of erasing the background image under the number, but it would look better with the 2-digit and 3-digit numbers centered, as illustrated above.  Thank you for agreeing to do this!

2) An option for **None** under **Dot type** would also be very useful, for cases where the number is needed but no dot is desired.

Thank you so much for your consideration and for such an excellent and useful program.

![Dot type use case](https://user-images.githubusercontent.com/55407804/149989035-6164f0c6-74e2-4317-842e-a5f6faa75619.png)

**Comment by maoschanz** [comment]
the idea of a variable size doesn't sound right however, if the number is centered and has an outline (like the text can have) to make it readable, would it be enough?

concerning this second suggestion, i can do this "none" type, meanwhile i think using pure transparency as a primary color could work fine

**Comment by jbergengh** [comment]
Yes, I think centering is all that is needed.  Centering would also make it easier to position 2 and 3-digit numbers more precisely, as they're centered on the first digit now.  Variable Size Dots was just another idea that popped into mind, and probably not a very good one.

Pure transparency for the dot's color is something I hadn't thought of.  Great idea.  I just tried it and that works perfectly.  That might make the **none** dot type unnecessary, but having a **none** type would still be easier for a user (like me) to comprehend, and quicker to select, vs the pure transparency.

Thanks again!
