### ISSUE TITLE
Port to libhandy

### ISSUE THREAD

**Issue by oscfdezdz** [maoschanz/drawing#480]
## Requested feature

Port Drawing to libhandy.

### Possible drawbacks

None, hopefully.

### Possible alternatives

None.

## Use case

Porting Drawing to libhandy would bring rounded bottom corners and with libhandy 1.5, support to officially follow system theme in GNOME 42 ([docs](https://gnome.pages.gitlab.gnome.org/libhandy/doc/main/HdyStyleManager.html)).

I've been trying to port it without much luck, the header bar is missing.

![imagen](https://user-images.githubusercontent.com/42654671/151432471-7058ba1f-7a25-4500-9b91-06aedbc4293f.png)

**Comment by maoschanz** [comment]
i think aiming for GTK4 (#220 ) is more important (and i think it achieves the weird corner thing too?)

**Comment by oscfdezdz** [comment]
Indeed, but libadwaita would also be required to follow system theme and I think for rounded corners also.

**Comment by maoschanz** [comment]
the goal of GTK4 is to be a cleaner, more modern, efficient, well designed, next-generation cross-platform toolkit. Libadwaita is a byproduct of these goals, and if i have to support it i will

but the goal of libhandy is just to bring responsiveness to gtk3... while Drawing is *already* responsive, i don't have to use it at all. So no, i will not make the app depend on libhandy: it would make packaging harder for nothing, the look of corners isn't worth the work, i usually don't even unmaximize the window 😅

**Comment by oscfdezdz** [comment]
Sorry to bother again about this issue but in GNOME 42, the system style is only changed with the dark style preference, it does not change the "legacy" theme as elementary OS seems to do. In GTK applications, the only way I know of to support that preference is with libhandy. This line of code is enough to support that preference (tested locally):

`Handy.StyleManager.get_default ().set_color_scheme(Handy.ColorScheme.PREFER_LIGHT)`

but it requires libhandy 1.6 (GNOME 42 runtime). It is not a complete port to libhandy but adds this feature for the new GNOME version.

**Comment by maoschanz** [comment]
i'm not sure what you're talking about (their newer gnome still have an unusable layout, so i stay with 3.38) but anyways, Drawing 1.0.0 is scheduled to be released on saturday, and i'll port the entire app to a new framework in 2 days

**Comment by oscfdezdz** [comment]
master:

![Grabación de pantalla desde 24-03-22 16 44 35](https://user-images.githubusercontent.com/42654671/159957283-9a09a69e-4738-46c5-ad0d-660e87d6bcc7.gif)

with [this commit](https://github.com/oscfdezdz/drawing/commit/e55f030c86717fa0936181bc3a4be3bb60bab211):

![Grabación de pantalla desde 24-03-22 16 45 19](https://user-images.githubusercontent.com/42654671/159957353-5ee7f248-dff6-451f-b2fa-cd83656bc3ce.gif)

Sorry for the quality of the GIFs 😅
