### ISSUE TITLE
compiling XML help; and/or getting other documentation

### ISSUE THREAD

**Issue by MaximLeyenson** [maoschanz/drawing#482]
Dear developers,

Thank you for your work on this project.

I have a couple of quetsions:

* How can I convert the XML documentation in the /usr/share/help/C/drawing  into something useful? 

(So far it is a bunch of files with extension .page, which appear to be XML. Could you add a script to convert them to html and preserve the interlinks?)

* Where do I get / find more documentation for the Drawing?

In particular, I am having perpetual issues with the Eraser tool (hard to figure out how to use it)

Thank you for all your work!

## System

- Device: Dsktop
- OS: Linux Mint
- Desktop environment: XFCE
- Package format:
- App version: 0.8.1

**Comment by maoschanz** [comment]
i don't know what you're looking for in /usr/share: just like any help pages they are easily accessible from within the app, by clicking on the "help" menu item or pressing F1

the gnome standard format for user documentation is [mallard](http://projectmallard.org/1.1/index.html), and i've no intention of developing scripts to replicate a worse version of their default help browser

>In particular, I am having perpetual issues with the Eraser tool (hard to figure out how to use it)

the help manual says:

>Eraser: Ignore the current color settings and just erase to get fully
        transparent pixels. Optionally, the erased pixels can be changed to the
        initial color of the canvas, or to the secondary color.

>Another option of this tool is its behavior: it can erase according
        to the line you draw with it, or according to a rectangular shape you
        define. Using this rectangle mode, you have more available options:
        blur, mosaic, randomly shuffle pixels, etc. so you can — for example —
        quickly censor text over wide areas of the image.
