### ISSUE TITLE
Popup message when closing Drawing without saving

### ISSUE THREAD

**Issue by amivaleo** [maoschanz/drawing#50]
Hi!

When you have unsaved changes in the open file and you close Drawing, you get this popup message:

![Schermata da 2019-06-14 10-55-52](https://user-images.githubusercontent.com/24316547/59497077-02cf7d80-8e93-11e9-8e6a-4e2bc4101626.png)

I suggest a few changes here, according to what other apps (well, mostly gedit) do:

- switch buttons position to ( Discard | Cancel | Save )
- change "Save" label to "Save As…"
- change "Discard" label to "Close without Saving"
- set the default selection on "Close without Saving"
- make "Close without Saving" a destructive button, i.e.: red background

<strike>(I'm going to submit the same issue about the "close without saving" background color in gedit right after I submit this)</strike>
I already did that some time ago...! 😄 https://gitlab.gnome.org/GNOME/gedit/issues/143

Are these changes ok for you? They are for making Drawing just a tiny bit more coherent with the other gnome apps. :)

**Comment by maoschanz** [comment]
Hello

>change "Save" label to "Save As…"
>change "Discard" label to "Close without Saving"

The dialogs are adaptative and using long labels could hurt the UX on mobile phones, especially with translations

>set the default selection on "Close without Saving"

It would lead to accidents, the default should be "Save"

>switch buttons position to ( Discard | Cancel | Save )

Ok, but only if there is a way to do that without "discard" being the default selection

>make "Close without Saving" a destructive button, i.e.: red background

Yes, good idea, i don't see how to do in the documentation however

**Comment by amivaleo** [comment]
> The dialogs are adaptative and using long labels could hurt the UX on mobile phones, especially with translations

You have a point here! I didn't think about this; you're right. I will submit issues for this gedit and other applications.

Keep "Discard". 💪

> It would lead to accidents, the default should be "Save"
Forgive me. I wrote the opposite than what I thought: the preselect button should be that save-button (as it is in gedit).

>  if there is a way to do that without "discard" being the default selection
There must be a way, since gedit does it. I can try to dig a bit, although I am not confident that I'd manage to find a solution... I'm not good in programming. :(

I'll let you know.

> i don't see how to do in the documentation however
I know that in Glade it's a style-class: open glade -> select the gtkbutton and add this property:
![Schermata da 2019-06-14 13-34-53](https://user-images.githubusercontent.com/24316547/59506716-43d28c80-8ea9-11e9-944e-b7203745a44e.png)
I guess this is not really helpful, since that dialog is not made using glade, but maybe it helps knowing that such red background comes from that "destructive-action" style-class.

**Comment by maoschanz** [comment]
>I guess this is not really helpful, since that dialog is not made using glade, but maybe it helps knowing that such red background comes from that "destructive-action" style-class.

It's how all other red buttons in the app are done, but this dialog is just the "GtkMessageDialog" class (it probably exists in Glade)

**Comment by amivaleo** [comment]
Maybe this can help: https://gitlab.gnome.org/GNOME/geary/merge_requests/183
There's a commit number there. Maybe the code there can help.

Forgive me, I am not able to do more than this. I hope you will succeed.

**Comment by maoschanz** [comment]
Aaah, ok it's not hard actually

**Comment by amivaleo** [comment]
Did it really help? :open_mouth: 

Wow, I'm glad I could help.
