### ISSUE TITLE
Edit PDFs

### ISSUE THREAD

**Issue by julianfairfax** [maoschanz/drawing#505]
## Requested feature

It would be nice if these features would work on PDFs, like how Preview works on macOS.

### Possible drawbacks

Maybe some people don't like PDFs?

### Possible alternatives

i could probably find another app, but not one as good.

## Use case

Occasionally I come across a PDF I'd like to quickly edit in a small way. When I used macOS, I would do this with Preview. Now that I'm on Linux, I don't know how to do it. It would be nice if I could with this app.

**Comment by maoschanz** [comment]
PDFs are not image at all, the main drawback is that the entire app should be rewritten lol

Sorry, this is out of the scope of what Drawing is

**Comment by Go-rom** [comment]
@julianfairfax [Xournal++](https://github.com/xournalpp/xournalpp) is what you're looking for
