### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by joostruis** [maoschanz/drawing#509]
- OS: Gentoo
[appsdrawing99992_spec-build.log](https://github.com/maoschanz/drawing/files/8436838/appsdrawing99992_spec-build.log)

**Comment by maoschanz** [comment]
is this trying to build from `master` or from `1.0.0`?

**Comment by joostruis** [comment]
Using this ebuild here:
https://data.gpo.zugaina.org/Miezhiko/media-gfx/drawing/drawing-9999.ebuild

**Comment by joostruis** [comment]
![Screenshot from 2022-04-07 02-02-40](https://user-images.githubusercontent.com/1949179/162094075-8659773c-a787-4c52-96e8-d1ee7d48c811.png)
Oh I needed to do this inception to point out the error. 
Thanks in advance!

**Comment by joostruis** [comment]
Now that I revisit the problem I think I know what causes the problem. I try to build this through an 3th party ebuild that "by luck" was able to successfully build drawing in my last build cycle. Now this ebuild does some funny stuff, like this:

https://github.com/Miezhiko/Overlay/blob/mawa/media-gfx/drawing/drawing-9999.ebuild#L44

Therefor my report is invalid. I am sorry that I did not notice this earlier!

**Comment by maoschanz** [comment]
ok i guess they were investigating an issue that i was fixing in parallel (the code from last week didn't work well with meson 0.61)

**Comment by Miezhiko** [comment]
yes...

**Comment by joostruis** [comment]
@Miezhiko now that you are here. Perhaps it is an idea to make an ebuild for version 1.0.0? Should work just fine.

**Comment by Miezhiko** [comment]
alright, maybe tomorrow

**Comment by maoschanz** [comment]
oops sorry i released the version 1.0.1 yesterday i didn't tell it here
