### ISSUE TITLE
The uri 'help:drawing/index' does not point to a valid page.

### ISSUE THREAD

**Issue by PJ-Singh-001** [maoschanz/drawing#518]
## Description

When I try to access help from the application menu, I get the message:

> Document not found.
> The uri 'help:drawing/index' does not point to a valid page.

### Steps to reproduce the bug

1. Install Drawing using `snap install drawing`.
2. Launch drawing.
3. Click the "hamburger" menu.
4. Select Help.
5. The GNOME Help application (Yelp, version 3.36.0) opens.
6. Help displays the error message:
   > Document not found.
   > The uri 'help:drawing/index' does not point to a valid page.

## System

- Device: laptop computer
- OS: Ubuntu 22.04
- Desktop environment: GNOME 42
- Package format: snap
- App version: 0.6.4

**Comment by maoschanz** [comment]
i guess it's probably related to the way snap sandboxing works? idk

Sorru but 0.6.4 is such an old version i'll not do any investigation on this: you should use a package format where the app is up-to-date
