### ISSUE TITLE
UI: switch "Preferences" and the Separator in the hamburger-menu

### ISSUE THREAD

**Issue by amivaleo** [maoschanz/drawing#52]
Hi!

Can you please switch the positions of the Separator and the Preferences button in the hamburger menu from this:

![a](https://user-images.githubusercontent.com/24316547/59961195-d17b3100-94d4-11e9-8c20-fc3e48db37c5.png)

to this:

![b](https://user-images.githubusercontent.com/24316547/59961196-d63fe500-94d4-11e9-84b0-014d4123bf07.png)

?

Most of gnome apps follow this order:

```
--------------
Preferences
Keyboard Shortcuts
Help
About APPNAME
```

Sorry for being pedant. ^_^

**Comment by maoschanz** [comment]
the goal of sections is to gather items with similar purposes, not to mimick other apps

There is "help" section, there is "preferences" section, i will not break them because other apps do something illogical since 3.32

**Comment by amivaleo** [comment]
I feel somewhat sorry even for asking.

Ok... Got it. 👋

**Comment by maoschanz** [comment]
no problem, it's normal to ask, i agree most apps are not doing this (but why ? they did separate sections within their appmenu a few months ago and appmenu removal guidelines say nothing about it)
