### ISSUE TITLE
UI: proposed Preferences window

### ISSUE THREAD

**Issue by amivaleo** [maoschanz/drawing#53]
Hi!

I've played a bit with Glade and I came up with this: 
[preferences.zip](https://github.com/maoschanz/drawing/files/3316664/preferences.zip)

It's the preferences.ui file, edited so that it looks a bit more gnomish, I think. 🤔

Take a look at that. It should work without any issue, but I haven't tested it.

If you like it, feel free to use or, if you want me to change something, please let me know. I like doing these things. :)

**Comment by maoschanz** [comment]
A little bit more gnomish, but... 480 pixels wide and not resizable, while it has to be 360

I'm not against naming sections with this kind of labels, but it comes with a very specific spacing _(like in Tweaks and the control center, which are what i guess you refer too when you say "more gnomish")_ so it's clear that the label is the title of its section despite being outside of it. Here you avoided the issue by removing ambiguously positionned titles

I think i'll redesign it for the next version

**Comment by amivaleo** [comment]
> it has to be 360

Why?

> 480 pixels wide and not resizable

It can be changed. I just made a try.

> like in Tweaks and the control center, which are what i guess you refer too when you say "more gnomish"

You guessed correctly. Those two are not the only ones, indeed. What I really care the most is to have the same "language design" everywhere. I don't really care about the language itself, I care about giving the users the idea of coherency among all the apps.

Not even Microsoft does that, I must say. So I see that it's an particular utopistic desire: free devs will never fully agree and follow the same rules that will limit their own freedom. That's fair. But it should worth saying that (in some matrix rooms, especially) instead of pretending that a huge common, fluent, coherent, innovative, whatever ecosystem might have any chance to become real, in Linux.

> you avoided the issue by removing ambiguously positionned titles

Not all the sections need a title. See gnome-control-center > Network (or Display or Wi-Fi, Notifications, etc).

As usual: discard this file completely or cherry pick. For me, it was funny to do. ;)

> i'll redesign it entirely for the next version

I guess I can close this issue then.

**Comment by maoschanz** [comment]
>Why?

https://developer.puri.sm/Librem5/Apps/Guides/Design/Constraints.html#screen-size

>Not all the sections need a title. 

When they don't, i don't add one. Here "opened image" is necessary to understand what the setting refers to, and "tools" is meant to grow

>I guess I can close this issue then.

I reopen it, else i would forget lol

**Comment by amivaleo** [comment]
> https://developer.puri.sm/Librem5/Apps/Guides/Design/Constraints.html#screen-size

I ignored that. My apologies.

I hope that you can grab some interesting idea from the file I did. 👍

**Comment by maoschanz** [comment]
in the end i decided to build the UI with the python code, the result is like this:

![Capture d’écran de 2019-06-22 23-37-02](https://user-images.githubusercontent.com/19996113/59969120-bba65400-9546-11e9-8018-560c92c14b5a.png)

![Capture d’écran de 2019-06-22 23-37-05](https://user-images.githubusercontent.com/19996113/59969119-bba65400-9546-11e9-9c43-1e48d6f961c7.png)

![Capture d’écran de 2019-06-22 23-37-08](https://user-images.githubusercontent.com/19996113/59969118-bba65400-9546-11e9-9e66-ddc8841d5fb3.png)

**Comment by amivaleo** [comment]
It is much more polish, indeed.

May I suggest to use a gear icon ("emblem-syste-symbolic") instead of the 3 dots? 🤔

**Comment by amivaleo** [comment]
Oh! Don't forget to put the units in the label. Like (px) for the "default width" label in the first page.

**Comment by maoschanz** [comment]
>May I suggest to use a gear icon ("emblem-syste-symbolic") instead of the 3 dots? thinking

Since the idea here is to view more options, i'll continue to use "view-more-horizontal-symbolic"

>Oh! Don't forget to put the units in the label. Like (px) for the "default width" label in the first page.

This shouldn't be in the labels, i opened #55

**Comment by amivaleo** [comment]
> Since the idea here is to view more options

I see. I thought they were "advanced" options. 👍

**Comment by maoschanz** [comment]
They are, so they are not system options
