### ISSUE TITLE
Shortcut function doesn't seem to be working well.

### ISSUE THREAD

**Issue by bdh1993** [maoschanz/drawing#540]
## Description

![image](https://user-images.githubusercontent.com/58254473/185524210-0ab7d8f8-fd67-49e2-8f93-1815ce0a3686.png)

1. The reason why this function is not possible is because of duplicate keys
![drawing](https://user-images.githubusercontent.com/58254473/185524468-bd7bab94-2f49-4fc7-bb23-5725a0d9193e.gif)

2. Shortcut keys do not work even if you change duplicate keys.
![drawing2](https://user-images.githubusercontent.com/58254473/185524518-3dac6b48-50f4-4019-a96e-fef996ecccac.gif)

### Steps to reproduce the bug

1. ... start drawing
2. ... open new tab
3. ... used Ctrl + Alt + Left or Right

## System

- Device : desktop, laptop, virtualbox
- OS: ubuntu 22.04, linuxmint 20, 21
- Package format native package from the distribution repository
- App version: 0.8.5 (help > about drawing)

**Comment by maoschanz** [comment]
sorry but "cinnamon uses ctrl/shift shortcuts instead of the super-key ones like any normal desktop environment, and prevent apps from using their own shortcuts even after it pretends the system-wide ones have been disabled" sounds a lot a series of Cinnamon issues and bugs

the app itself is working fine.

**Comment by maoschanz** [comment]
nevermind! i understood the issue: it works on my machine because... i know the actual shortcuts are ctrl+shift+arrow 😅

the help window listing the shortcuts is wrong

**Comment by bdh1993** [comment]
Thank you maoschanz.
I think I can use it more conveniently.
