### ISSUE TITLE
Blur toggle doesn't work

### ISSUE THREAD

**Issue by sujaldev** [maoschanz/drawing#541]
## Description
![UI](https://user-images.githubusercontent.com/75830554/185532841-132dbb05-40cf-49b3-ad11-ac526a7970a9.png)

Clicking on the blur toggle doesn't toggle back off once enabled.

#### Traceback
```python
Traceback (most recent call last):
  File "/app/share/drawing/drawing/window.py", line 208, in _update_active_tool_from_flowbox_signal
    self.switch_to(selected_tool.id)
  File "/app/share/drawing/drawing/window.py", line 918, in switch_to
    self.set_window_subtitles()
  File "/app/share/drawing/drawing/window.py", line 652, in set_window_subtitles
    subtitles_list = self.active_tool().get_editing_tips()
  File "/app/share/drawing/drawing/tool_text.py", line 94, in get_editing_tips
    bg_label = {
KeyError: 'outline'
```

### Steps to reproduce the bug

1. Choose eraser
2. Open Eraser Options and switch to selection mode (or whatever the box logo is meant for)
3. Toggle Blur

## System

- Device: Desktop Computer
- OS: Fedora 36
- Desktop environment: GNOME
- Package format: flatpak
- App version: 1.0.1

**Comment by maoschanz** [comment]
>Clicking on the blur toggle doesn't toggle back off once enabled.

i'm not sure what you mean...

i can't reproduce any bug around the eraser tool, it can blur a rectangle area just fine

----

however, i know what the stack trace is about: you should go to the **text** tool, select a valid value for the background (the default one isn't valid, sorry...), and close the app so it retains the new valid value

**Comment by sujaldev** [comment]
Sorry if I phrased it wrong, I mean't once you enable the blur option, it can't be disabled anymore. Like this:


![demo](https://user-images.githubusercontent.com/75830554/185638385-00169580-b153-498f-ae08-73be1968399a.gif)
