### ISSUE TITLE
Show selected area in filter mode

### ISSUE THREAD

**Issue by sonicnkt** [maoschanz/drawing#577]
## Description

So i was looking for a simple image annotation tool for screenshots  annotations.
A typical task for me is to select an area and make it non legible.
Here i am encountering the following odd behaviour:
Either the selected area is not shown at all when switching to the Filter mode or the selected area is black.
Applying the filter by clicking on the area works fine tho.

Since i have never used the app before i am not sure what is supposed to be the default behaviour but since it changes on its own there seems to be some bug going on. 

Here are some screenshots:
![grafik](https://user-images.githubusercontent.com/5454622/212484961-bc01fec6-b817-4301-8f21-9591ef5d4698.png)
![grafik](https://user-images.githubusercontent.com/5454622/212485085-a1d46998-3ae3-462b-89b8-8390e841b21e.png)
![grafik](https://user-images.githubusercontent.com/5454622/212485056-c80408dc-40e0-4760-9619-319461de4726.png)

### Steps to reproduce the bug

1. Open Image
2. Select Area (rectangle or free)
3. Switch to Filter mode
4. The selected area is not displayed (highlighted?)
5. Return to Select Area mode (RED back button)
6. Click on Filters again
7. Now the selected area is displayed black.

## System
- Device: Desktop PC, X86_64, AMD GPU with Mesa drivers
- OS: Fedora 37
- Desktop environment: Gnome 43, Wayland Session
- Package format: native
- App version: 1.0.1

**Comment by maoschanz** [comment]
yes it's a bug, it happens only with the blurring filters tho

the normal behavior is to immediately preview the selected filter with the selected options (by default: saturation at 100%, aka no changes at all), but computing blur in python is painfully slow so when the filter is this one, the app doesn't try anything unless you click

for the next version i'll show the unblurred image by default i think, but eventually i should look for a less naive way to apply convolutions to an image lol

**Comment by sonicnkt** [comment]
Ah in understand :) i must have missed the default behaviour since i immediately set it to blur/mosaic for my common workflow.  Thanks for looking into this!
