### ISSUE TITLE
Add Line with arrow on both ends

### ISSUE THREAD

**Issue by linuxr01** [maoschanz/drawing#59]
![grafik](https://user-images.githubusercontent.com/49744994/60706229-499c1a80-9f09-11e9-8cdb-e6731f0bd78c.png)

**Comment by maoschanz** [comment]
i sometimes wonder why i even wrote issues templates

**Comment by linuxr01** [comment]
What information is missing?

**Comment by maoschanz** [comment]
It's clear, just... wordless 😅
