### ISSUE TITLE
Great Program - but there is no setting sizes of fonts.

### ISSUE THREAD

**Issue by Me2U2** [maoschanz/drawing#604]
It needs a way to set the sizes of fonts AND to move them around.

Other than that - it's very good.

**Comment by maoschanz** [comment]
>set the sizes

you can use the same widget as to change the pencil thickness: the value of the font size will be 2 times the value in the input 

>move them around

this is being fixed, with issue #357 which should be released soon

**Comment by maoschanz** [comment]
i think you couldn't understand how the size-changing input applied to the text because the 1.0 implementation of the text tool expects a new click from the user before refreshing the preview. This will also be fixed  by #357
