### ISSUE TITLE
Pleas add a paint bucket tool

### ISSUE THREAD

**Issue by TriVoxel** [maoschanz/drawing#611]
## Requested feature

I'd like a paint bucket tool similar to MS Paint and most other drawing software.

### Possible drawbacks

It might not be super easy.

### Possible alternatives

**There is no alternative!!!**

But, seriously. This is one of my most used tools when using similar programs like MS Paint. To me, a fill tool/paint bucket tool is essential to a simple drawing program to easily color in entire shapes. This is the only thing holding me back from really using this app.

## Use case

For people drawing simple shapes, characters, blueprints, etc., having a fill tool to conveniently fill intersecting lines, same-colored pixels with a defined border, etc. is crucial. Otherwise, the user needs to spend ages drawing inside the lines to add colors. This is very important for artists sketching characters for instance. If you wanted to get real fancy, you could add some color bleed, sensitivity, etc. to make the tool more useful. I'd be perfectly content with a simple tool that only fills same-colored pixels with a border though.

**Comment by TriVoxel** [comment]
Okay, I guess this just isn't enabled by default for some reason?

**Comment by maoschanz** [comment]
the reason being that it currently sucks 😅

i opened #616 for the future new implementation
