### ISSUE TITLE
GNOME 43 runtime is no longer supported as of September 20 2023

### ISSUE THREAD

**Issue by TNTBOMBOM** [maoschanz/drawing#618]
### Steps to reproduce the bug

```
user@host:~$ flatpak update 
Looking for updates…

Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.maoschanz.drawing
```

## System

- Device (desktop computer/tablet/phone/...): PC
- OS: Debian 12
- Desktop environment: Xfce
- Package format: flatpak
- App version: latest

**Comment by macdar** [comment]
I don't have this issue on Debian 12 with Gnome. Could you check installed version of `org.gnome.Platform'? I see 44 and 45 branches.

**Comment by maoschanz** [comment]
oh shit i thought i was using the 44

**Comment by maoschanz** [comment]
nevermind, @bbhtt updated it

**Comment by TNTBOMBOM** [comment]
> nevermind, @bbhtt updated it

I can see this commit here: 

https://github.com/flathub/com.github.maoschanz.drawing/commit/4af68ec53271daad17f1e7b2202049d36eb3e676

but this didnt resolve the issue after i upgraded drawing, still getting the same notification.
