### ISSUE TITLE
Persistant window size

### ISSUE THREAD

**Issue by in4matix** [maoschanz/drawing#634]
## Persistent Application windows size  

What determines the size of the Application window? Currently, irrespective of canvas size, the App window will always start with a default size that is too small.

## Suggested solution

I suggest adding the ability for the App to "remember" the last set window size, so when it is opened again, it will open with the last saved window size.

### Possible drawbacks

None that I can think of.

### Possible alternatives

None that I can think of.

**Comment by maoschanz** [comment]
>always

not exactly: it opens a maximized window if your last closed window was maximized.

I think it satisfies all people who want a window as big as possible, your suggestion is useful if you're using tiling but it's not high priority

**Comment by in4matix** [comment]
I never use any App maximized as I have a large monitor and mostly have many Apps open that I jump between. I like to have access to at least partial desktop while working in Applications. All other Apps that I use "remember" the last window size set and open in that size. Is there any way to alter the current minimum window size, maybe in a settings file?

**Comment by maoschanz** [comment]
no there isn't yet sorry
