### ISSUE TITLE
Toolpanel width not reset when disabling tools names

### ISSUE THREAD

**Issue by rndtrash** [maoschanz/drawing#68]
## Description

When disabling tools names, items in toolbar are still wide.

## Steps to reproduce the bug:

1. Open the settings menu
2. Go to "Tools" tab
3. Disable tools names

## Expected behavior

Toolbar should not be wide.

## Screenshots

![s0](https://user-images.githubusercontent.com/6745157/61969986-7f05c680-afe4-11e9-90b2-9991c48d53f4.png)
----
![s1](https://user-images.githubusercontent.com/6745157/61969988-7f05c680-afe4-11e9-8cbb-f2ff5c40b2af.png)
----
![s2](https://user-images.githubusercontent.com/6745157/61969990-7f9e5d00-afe4-11e9-940d-e23182c2b7c7.png)

## System

- Device (desktop computer/tablet/phone/...): desktop computer
- OS: Ubuntu 19.04
- Desktop environment: none
- Package format (flatpak, DEB, AUR ?): deb
- App version: 0.4.1

## Additional context

--

Sorry for my poor English :P

**Comment by maoschanz** [comment]
>1. Open the settings menu
>2. Go to "Tools" tab
>3. Disable tools names

It bugs too when you just change it from the primary menu

----

Is the size correct when you open a new window?

By the way, you're the first known person to test this deb package, does it work without issues?

**Comment by rndtrash** [comment]
>Is the size correct again when you open a new window?

Yes.
![s3](https://user-images.githubusercontent.com/6745157/61977244-9fd71780-aff6-11e9-808a-aebc6447bd63.png)


>By the way, you're the first known person to test this deb package, does it work without issues?

I think so. Creating, loading, editing and saving pictures works fine, settings are saved, help window works, no errors in console :ok_hand:

**Comment by maoschanz** [comment]
damn, is there really no shorter translation than предварительный просмотр ?

**Comment by rndtrash** [comment]
>предварительный просмотр

There is a shorter version
"Предпросмотр"
But it sounds not as formal

**Comment by maoschanz** [comment]
As long as it makes the "preview" button narrow enough to allow the UI to shrink, it's fine

**Comment by rndtrash** [comment]
OK then, I think it fits perfectly :smile:

**Comment by rndtrash** [comment]
(Sorry, missclick)

**Comment by rndtrash** [comment]
![Снимок экрана_2019-07-27_14-51-06](https://user-images.githubusercontent.com/6745157/61994043-ffc4d100-b07d-11e9-9273-5e8015acb2bd.png)
![Снимок экрана_2019-07-27_14-50-46](https://user-images.githubusercontent.com/6745157/61994044-ffc4d100-b07d-11e9-8c25-1dcb1ac66d94.png)

BTW, the preview button is shrinking too early when resized manualy.
Though I think that's different issue.

**Comment by maoschanz** [comment]
I think it's the same issue with that label, with the selection the shrinking is triggered if the width is smaller than a fixed value, and for the other tools the shrinking is triggered if the width is smaller than [some percentage] of the width of the existing widgets.

**Comment by maoschanz** [comment]
The fix will be available with the version 0.4.2
