### ISSUE TITLE
Non-semantic icons for almost everything

### ISSUE THREAD

**Issue by cassidyjames** [maoschanz/drawing#7]
It looks like you're requesting the non-semantic `network-transmit-receive-symbolic` icon to represent something like swapping colors.

![image](https://user-images.githubusercontent.com/611168/51876351-8bef7900-2325-11e9-8175-24dcd468d5ef.png)

It would be better to find a standardized semantic icon, or to GResource a double-arrow icon if that's what you want it to look like visually.

**Comment by maoschanz** [comment]
i began to add icons in the gresource, but i'm really bad at inkscape so i'm doing it slowly. There are actually inadequate icons for most tools (and the app icon is still an ugly improvisation but that is an other issue)
