### ISSUE TITLE
The DEB package doesn't specify the minimal versions of its dependencies

### ISSUE THREAD

**Issue by gechandesu** [maoschanz/drawing#70]
## Description

I can't launch the app installed from the deb package.

When I try launch it from terminal I recieve this:

```
Traceback (most recent call last):
  File "/usr/bin/drawing", line 42, in <module>
    from drawing import main
  File "/usr/share/drawing/drawing/main.py", line 23, in <module>
    from .window import DrawingWindow
  File "/usr/share/drawing/drawing/window.py", line 40, in <module>
    from .image import DrawingImage
  File "/usr/share/drawing/drawing/image.py", line 31, in <module>
    @Gtk.Template(resource_path='/com/github/maoschanz/drawing/ui/image.ui')
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'
```
Also app don't shown in Slingshot. 

## Steps to reproduce the bug:

1. Install the deb package
2. Do nothing

----

## System

- Device: desktop computer
- OS: elementary OS 5.0 Juno (with latest updates)
- Desktop environment: Pantheon
- Package format (flatpak, DEB, AUR ?): DEB
- App version: 0.4.1

## Additional context

No installation errors:

```
gd@eos:~$ sudo dpkg -i '/home/gd/Загрузки/drawing_0.4.1_amd64.deb' 
Выбор ранее не выбранного пакета drawing.
(Чтение базы данных … на данный момент установлено 311867 файлов и каталогов.)
Подготовка к распаковке …/drawing_0.4.1_amd64.deb …
Распаковывается drawing (0.4.1) …
Настраивается пакет drawing (0.4.1) …
Обрабатываются триггеры для desktop-file-utils (0.23-1ubuntu3.18.04.2+elementary2~ubuntu5.0.1) …
Обрабатываются триггеры для gnome-menus (3.13.3-11ubuntu1.1) …
Обрабатываются триггеры для bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) …
Rebuilding /usr/share/applications/bamf-2.index...
Обрабатываются триггеры для mime-support (3.60ubuntu1) …
Обрабатываются триггеры для libglib2.0-0:i386 (2.56.4-0ubuntu0.18.04.4) …
Обрабатываются триггеры для libglib2.0-0:amd64 (2.56.4-0ubuntu0.18.04.4) …
Обрабатываются триггеры для hicolor-icon-theme (0.17-2) …
```

**Comment by rndtrash** [comment]
Have you tried `sudo apt-get install -f`?

**Comment by maoschanz** [comment]
it looks like a specific version of python3-gi is needed, which is proposed on Debian Sid and Ubuntu 19.04 but not on elementary Juno (and i forgot to write it in the control file https://github.com/maoschanz/drawing/blob/c46edf52c076eb9cfe0b942e75c31c749b9ae162/debian/control#L11 )

**Comment by gechandesu** [comment]
@rndtrash 
> Have you tried `sudo apt-get install -f`?

This does not work.

**Comment by gechandesu** [comment]
@maoschanz

**Comment by maoschanz** [comment]
> it looks like a specific version of python3-gi is needed, which is proposed on Debian Sid and Ubuntu 19.04 but not on elementary Juno (and i forgot to write it in the control file https://github.com/maoschanz/drawing/blob/c46edf52c076eb9cfe0b942e75c31c749b9ae162/debian/control#L11 )

And the needed version is 3.30, which is really not available on Bionic or Juno, so the app is only available as flatpak on these plateforms, sorry
