### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by dykow** [maoschanz/drawing#76]
It would be great to be able to paste image into _Drawing_ from clipboard.

**Comment by maoschanz** [comment]
you can already do

- *Selection > bottom bar > Paste* or *Selection > right click > Paste*
- *New Image > From Clipboard*

Or ctrl+v: if you're not using the text tool (where ctrl+v pastes text) it should change the current tool to the selection and paste the image in your clipboard
