### ISSUE TITLE
Flathub description seems to be cut off

### ISSUE THREAD

**Issue by anoadragon453** [maoschanz/drawing#79]
![image](https://user-images.githubusercontent.com/1342360/62396252-93a90800-b56a-11e9-9f99-0169c45aee76.png)

**Comment by maoschanz** [comment]
And the funniest part is that GNOME Software cut it off too, but not in the same way

**Comment by maoschanz** [comment]
holy shit https://snapcraft.io/drawing

**Comment by ericoporto** [comment]
@maoschanz you are doing very interesting and good software here. When I looked into snapping I hit some trouble and [asked on the forums](https://forum.snapcraft.io/t/trying-to-snap-drawing/12585/11) and apparently it's hitting some interesting bugs on snapcraft side. What you are seeing is in edge channel, and still work in progress.

**Comment by maoschanz** [comment]
Runtime 3.28 but python3-gi must be >=3.30

Not the point of this issue anyway, this issue is about the horrific rendering of the appdata description, which is "correct" according to appstream-util but actually it looks obvious that it doesn't support `ul` tags inside `p` tags

**Comment by ericoporto** [comment]
I deleted the message to not switch the point of this issue. :)

**Comment by maoschanz** [comment]
fixed https://flathub.org/apps/details/com.github.maoschanz.drawing ?
