### ISSUE TITLE
ask for size when creating a new image

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#81]
## Problem

![Capture d’écran de 2019-08-03 00-46-41](https://user-images.githubusercontent.com/19996113/62402492-4340a300-b588-11e9-8bbe-aa358e4385ff.png)

## Suggested solution

2 menu items:

- new blank image
- new blank image (???×???)

The first asks the size, the other doesn't

### Possible drawbacks

Dialogs are shit

### Possible alternatives

widgets on the canvas

**Comment by alex285** [comment]
New Image and  then a dialog with dimensions? as it works everywhere?

**Comment by maoschanz** [comment]
>everywhere

Not in Microsoft Paint or KolourPaint

**Comment by alex285** [comment]
> Not in Microsoft Paint or KolourPaint

i guess there is nothing we can say to such argument :p

**Comment by maoschanz** [comment]
![Capture d’écran de 2019-10-22 04-56-03](https://user-images.githubusercontent.com/19996113/67256605-562c8a80-f488-11e9-89d6-fda5177b504d.png)

it will look like this
