### ISSUE TITLE
Please provide an AppImage

### ISSUE THREAD

**Issue by probonopd** [maoschanz/drawing#86]
## Problem

I cannot easily download and run Drawing like I can e.g., [Krita](https://krita.org/en/download/krita-desktop/).

## Suggested solution

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### Possible drawbacks

None.

### Possible alternatives

None that match the feature set described above.

**Comment by maoschanz** [comment]
## Possible drawbacks

- I don't see the point of wasting my time with this.
- Each app managing its own updates is a dangerous mess.
- Normal users launch their app from the DE menu, not from the file manager.
- The normal location for this kind of mess is `/opt`, but it belongs to root, thus breaking the possibility to have both a clean system AND updates at the same time.

## Possible alternatives

Use flatpak to run it on many distributions with no system librairies changed and a perfect system integration. It's decentralized too, and the runtime is the same as all other GNOME apps so it should already be here.

----

So it's a no. But you can package it as an appimage yourself if you want, i let the issue open if you have questions regarding the dependencies

**Comment by probonopd** [comment]
> I don't see the point of wasting my time with this.

Would you entertain a pull request that would do all the work for you?

> Each app managing its own updates is a dangerous mess.

Your opinion, not mine.

> Normal users launch their app from the DE menu, not from the file manager.

The optional appimaged daemon or thrid-party solutions like AppImageLauncher can put it in the menu automatically. (Side note, the Freedesktop XDG stuff lacks behind what the Mac and Haiku offer, so it's really a crude workaround)

> The normal location for this kind of mess is /opt, but it belongs to root, thus breaking the possibility to have both a clean system AND updates at the same time.

AppImages run from anywhere, including $HOME, $HOME/bin, $HOME/Downloads, removable drives, and network shares. Just from anywhere...!

**Comment by maoschanz** [comment]
>Your opinion, not mine.

My opinion is the opinion of the guy who will have to deal with issues from obsolete versions of his app for years because with appimages, every component providing basic package management features is optional (= less than 1% of users have it)

>AppImages run from anywhere, including $HOME, $HOME/bin, $HOME/Downloads, removable drives, and network shares. Just from anywhere...!

I understood you home folder was chaos, now the questions are:

- do i want to support fragmentation?
- do i want to support the kind of fragmentation where apps behave like Windows' .exe files?

>This is an option to do in addition, but it is not an alternative because it cannot do what AppImage does.

I correct your typo: AppImage is an option to do in addition, but it is not an alternative because it cannot do what all other packaging systems do.

>I have no GNOME apps on my system.

Convenient coincidence

>Would you entertain a pull request that would do all the work for you?

It depends on the pull request content, if it's just one or two script ok. But i would not "compile" or distribute such a package anyway

**Comment by probonopd** [comment]
> AppImage is an option to do in addition, but it is not an alternative because it cannot do what all other packaging systems do.

We can totally agree on this one: The systems are complements, not substitutes.

**Comment by probonopd** [comment]
> But i would not "compile" or distribute such a package anyway

Well, the whole point of AppImage is that the application author (you) can provide and _support_ a downloadable executable and control the whole experience of it ("upstream packaging"). Looks like you are not interested in that.

**Comment by maoschanz** [comment]
Yes, sorry but my upstream package already exists, it's the flatpak one, which is use. Then, the rest (Ubuntu PPA, Fedora main repo, Arch Community repo, etc.) is managed by people using these package formats themselves. It would be weird to do an exception for a package format that i don't even consider as a valid way to provide an app...
