### ISSUE TITLE
Please enable arm64 and armhf builds in PPA

### ISSUE THREAD

**Issue by RussianNeuroMancer** [maoschanz/drawing#87]
## Problem

Currently only amd64 and i386 builds are enabled in PPA settings. I tried to [rebuild Drawing packages for arm64 and armhf architectures](https://launchpad.net/~russianneuromancer/+archive/ubuntu/ppa/+packages), and tested arm64 build on Lenovo Yoga C630 WOS with Ubuntu 19.04 (build with [this scripts](https://github.com/aarch64-laptops/build)). Long story short, it's seems like it just works after rebuilding.

## Suggested solution

Please visit this page, scroll down, enable "ARM ARMv8 (arm64)" and "ARM ARMv7 Hard Float (armhf)" in Processors section, press Save at the bottom of the page. When you upload next version it will be automatically build for four processor architectures. 

https://launchpad.net/~cartes/+archive/ubuntu/drawing/+edit

### Possible drawbacks

I didn't test arm64 build extensively and didn't test armhf build at all. There is possibility that some feature (or few features) could be broken in arm64 build and cause unhanded exception or just misbehave. However, my bold assumption is that chances of negative outcome with Python is pretty low.

### Possible alternatives

Provide arm64 and armhf bulds in flatpak.

**Comment by maoschanz** [comment]
Flathub builds packages for "arm" and "aarch64", i'm not sure what exact kinds of ARM are provided here

Concerning the PPA, it's an issue for @frenchy82 (i hope it's actually his github account)

**Comment by RussianNeuroMancer** [comment]
> Flathub builds packages for "arm" and "aarch64"

Good to know, I missed this.

**Comment by frenchy82** [comment]
Thanks a lot RussianNeuroMancer for the report, it really helps me

I've edited the  drawing ppa in the processors section so, as you said, so it will be ready for the next version unless you think it needs to be rebuild with this version

**Comment by RussianNeuroMancer** [comment]
Thank you!
